# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.LinerStageFactorService_pb2_grpc as LinerStageFactorService_pb2_grpc
class GeosyntheticBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getTensileModulus(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Tensile_modulus")
    def setTensileModulus(self, value: float):
        self._propertyAccessor.setDoubleProperty("Tensile_modulus", value)
    def getTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Tensile_strength_peak")
    def setTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("Tensile_strength_peak", value)
    def getResidualTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Tensile_strength_residual")
    def setResidualTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("Tensile_strength_residual", value)
    def getProperties(self):
        return {
            "TensileModulus": self.getTensileModulus(),
            "TensileStrength": self.getTensileStrength(),
            "ResidualTensileStrength": self.getResidualTensileStrength(),
        }
    def setProperties(self, TensileModulus: float = None, TensileStrength: float = None, ResidualTensileStrength: float = None):
        if TensileModulus is not None:
            self.setTensileModulus(TensileModulus)
        if TensileStrength is not None:
            self.setTensileStrength(TensileStrength)
        if ResidualTensileStrength is not None:
            self.setResidualTensileStrength(ResidualTensileStrength)
class GeosyntheticStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, LinerStageFactorService_pb2_grpc.LinerStageFactorServiceStub(client.channel))
    def getTensileModulusFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Geosynthetic_TensileModulus")
    def getTensileStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Geosynthetic_TensileStrength")
    def getResidualTensileStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Geosynthetic_TensileStrengthResidual")
class GeosyntheticDefinedStageFactorBase(GeosyntheticStageFactorBase):
    def setTensileModulusFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Geosynthetic_TensileModulus", value)
    def setTensileStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Geosynthetic_TensileStrength", value)
    def setResidualTensileStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Geosynthetic_TensileStrengthResidual", value)

################ Code below this line will not be overridden ################
from rs3.properties.stageFactors.StageFactorInterfaces import RelativeStageFactorInterface
from rs3.properties.PropertyEnums import *

class GeosyntheticStageFactor(GeosyntheticStageFactorBase):
    """
	Examples:
		See :ref:`liner_example`.
	"""
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
    
class GeosyntheticDefinedStageFactor(GeosyntheticStageFactor, GeosyntheticDefinedStageFactorBase):
    """
	Examples:
		See :ref:`liner_example`.
	"""
    pass

class Geosynthetic(GeosyntheticBase):
    """
	Examples:
		See :ref:`liner_example`.
	"""
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self.StageFactorInterface = RelativeStageFactorInterface[GeosyntheticDefinedStageFactor, GeosyntheticStageFactor](id, client, GeosyntheticDefinedStageFactor, GeosyntheticStageFactor)
        
    def getMaterialType(self) -> MaterialType:
        return MaterialType(self._propertyAccessor.getBoolValue("IsPlastic"))
    def setMaterialType(self, value: MaterialType):
        self._propertyAccessor.setBoolValue("IsPlastic", value.value)