# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
class UniformBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getUniformMeshElementSize(self) -> float:
        return self._propertyAccessor.getDoubleProperty("UniformMeshElementSize")
    def setUniformMeshElementSize(self, value: float):
        self._propertyAccessor.setDoubleProperty("UniformMeshElementSize", value)
    def getProperties(self):
        return {
            "UniformMeshElementSize": self.getUniformMeshElementSize(),
        }
    def setProperties(self, UniformMeshElementSize: float = None):
        if UniformMeshElementSize is not None:
            self.setUniformMeshElementSize(UniformMeshElementSize)

################ Code below this line will not be overridden ################
from rs3.mesh.MeshEnums import *
class Uniform(UniformBase):
    """
	Examples:
		See :ref:`mesh_example`.
    """
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        
    def getMeshDensity(self) -> MeshDensity:
        return self._propertyAccessor.getEnumValue("MeshDensity", MeshDensity)
    def setMeshDensity(self, meshDensity : MeshDensity):
        self._propertyAccessor.setEnumValue("MeshDensity", meshDensity.value)