# Generated by RPCBinder in RFC_Common.
import rs3.generatedFiles.ModelService_pb2_grpc as ModelServiceGrpc
import rs3.generatedFiles.ModelService_pb2 as ModelService
from rs3._client import Client

class ModelBase:
    def __init__(self, client: Client, _projectId: str):
        self._client = client
        self._projectId = _projectId
        self._ModelService = ModelServiceGrpc.ModelServiceStub(self._client.channel)
    def save(self) -> None:
        _projectId_ = self._projectId
        request = ModelService.saveRequest(_projectId=_projectId_)
        self._client.callFunction(self._ModelService.save, request)
    
    def saveAs(self, newLocation: str) -> None:
        _projectId_ = self._projectId
        newLocation_ = newLocation
        request = ModelService.saveAsRequest(_projectId=_projectId_, newLocation=newLocation_)
        self._client.callFunction(self._ModelService.saveAs, request)
    
    def close(self, saveProject: bool) -> None:
        _projectId_ = self._projectId
        saveProject_ = saveProject
        request = ModelService.closeRequest(_projectId=_projectId_, saveProject=saveProject_)
        self._client.callFunction(self._ModelService.close, request)
    
    def saveComputeFile(self) -> None:
        _projectId_ = self._projectId
        request = ModelService.saveComputeFileRequest(_projectId=_projectId_)
        self._client.callFunction(self._ModelService.saveComputeFile, request)
    
    def setActiveStageByName(self, stageName: str) -> None:
        _projectId_ = self._projectId
        stageName_ = stageName
        request = ModelService.setActiveStageByNameRequest(_projectId=_projectId_, stageName=stageName_)
        self._client.callFunction(self._ModelService.setActiveStageByName, request)
    
    def getActiveStageName(self) -> str:
        _projectId_ = self._projectId
        request = ModelService.getActiveStageNameRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getActiveStageName, request)
        result = result_.result
        return result
    
    def setActiveStage(self, stageNum: int) -> None:
        _projectId_ = self._projectId
        stageNum_ = stageNum
        request = ModelService.setActiveStageRequest(_projectId=_projectId_, stageNum=stageNum_)
        self._client.callFunction(self._ModelService.setActiveStage, request)
    
    def getActiveStage(self) -> int:
        _projectId_ = self._projectId
        request = ModelService.getActiveStageRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getActiveStage, request)
        result = result_.result
        return result
    
    def getBoltPropertyByName(self, boltName: str) -> str:
        _projectId_ = self._projectId
        boltName_ = boltName
        request = ModelService.getBoltPropertyByNameRequest(_projectId=_projectId_, boltName=boltName_)
        result_ = self._client.callFunction(self._ModelService.getBoltPropertyByName, request)
        result = result_.result
        return result
    
    def getBeamPropertyByName(self, beamName: str) -> str:
        _projectId_ = self._projectId
        beamName_ = beamName
        request = ModelService.getBeamPropertyByNameRequest(_projectId=_projectId_, beamName=beamName_)
        result_ = self._client.callFunction(self._ModelService.getBeamPropertyByName, request)
        result = result_.result
        return result
    
    def getLinerPropertyByName(self, linerName: str) -> str:
        _projectId_ = self._projectId
        linerName_ = linerName
        request = ModelService.getLinerPropertyByNameRequest(_projectId=_projectId_, linerName=linerName_)
        result_ = self._client.callFunction(self._ModelService.getLinerPropertyByName, request)
        result = result_.result
        return result
    
    def getJointPropertyByName(self, jointName: str) -> str:
        _projectId_ = self._projectId
        jointName_ = jointName
        request = ModelService.getJointPropertyByNameRequest(_projectId=_projectId_, jointName=jointName_)
        result_ = self._client.callFunction(self._ModelService.getJointPropertyByName, request)
        result = result_.result
        return result
    
    def getLiningCompositionPropertyByName(self, compositeLinerName: str) -> str:
        _projectId_ = self._projectId
        compositeLinerName_ = compositeLinerName
        request = ModelService.getLiningCompositionPropertyByNameRequest(_projectId=_projectId_, compositeLinerName=compositeLinerName_)
        result_ = self._client.callFunction(self._ModelService.getLiningCompositionPropertyByName, request)
        result = result_.result
        return result
    
    def getPilePropertyByName(self, pileName: str) -> str:
        _projectId_ = self._projectId
        pileName_ = pileName
        request = ModelService.getPilePropertyByNameRequest(_projectId=_projectId_, pileName=pileName_)
        result_ = self._client.callFunction(self._ModelService.getPilePropertyByName, request)
        result = result_.result
        return result
    
    def getMaterialPropertyByName(self, materialName: str) -> str:
        _projectId_ = self._projectId
        materialName_ = materialName
        request = ModelService.getMaterialPropertyByNameRequest(_projectId=_projectId_, materialName=materialName_)
        result_ = self._client.callFunction(self._ModelService.getMaterialPropertyByName, request)
        result = result_.result
        return result
    
    def getWaterByLocationPropertyByName(self, waterSurfaceName: str) -> str:
        _projectId_ = self._projectId
        waterSurfaceName_ = waterSurfaceName
        request = ModelService.getWaterByLocationPropertyByNameRequest(_projectId=_projectId_, waterSurfaceName=waterSurfaceName_)
        result_ = self._client.callFunction(self._ModelService.getWaterByLocationPropertyByName, request)
        result = result_.result
        return result
    
    def getWaterGridPropertyByName(self, waterGridName: str) -> str:
        _projectId_ = self._projectId
        waterGridName_ = waterGridName
        request = ModelService.getWaterGridPropertyByNameRequest(_projectId=_projectId_, waterGridName=waterGridName_)
        result_ = self._client.callFunction(self._ModelService.getWaterGridPropertyByName, request)
        result = result_.result
        return result
    
    def getExternalVolumeByName(self, externalVolumeName: str) -> str:
        _projectId_ = self._projectId
        externalVolumeName_ = externalVolumeName
        request = ModelService.getExternalVolumeByNameRequest(_projectId=_projectId_, externalVolumeName=externalVolumeName_)
        result_ = self._client.callFunction(self._ModelService.getExternalVolumeByName, request)
        result = result_.result
        return result
    
    def getDiscreteFunctionByName(self, discreteFunctionName: str) -> str:
        _projectId_ = self._projectId
        discreteFunctionName_ = discreteFunctionName
        request = ModelService.getDiscreteFunctionByNameRequest(_projectId=_projectId_, discreteFunctionName=discreteFunctionName_)
        result_ = self._client.callFunction(self._ModelService.getDiscreteFunctionByName, request)
        result = result_.result
        return result
    
    def getShearNormalFunctionByName(self, shearNormalFunctionName: str) -> str:
        _projectId_ = self._projectId
        shearNormalFunctionName_ = shearNormalFunctionName
        request = ModelService.getShearNormalFunctionByNameRequest(_projectId=_projectId_, shearNormalFunctionName=shearNormalFunctionName_)
        result_ = self._client.callFunction(self._ModelService.getShearNormalFunctionByName, request)
        result = result_.result
        return result
    
    def getGeneralizedAnisotropicFunctionByName(self, generalizedAnisotropicFunctionName: str) -> str:
        _projectId_ = self._projectId
        generalizedAnisotropicFunctionName_ = generalizedAnisotropicFunctionName
        request = ModelService.getGeneralizedAnisotropicFunctionByNameRequest(_projectId=_projectId_, generalizedAnisotropicFunctionName=generalizedAnisotropicFunctionName_)
        result_ = self._client.callFunction(self._ModelService.getGeneralizedAnisotropicFunctionByName, request)
        result = result_.result
        return result
    
    def getCustomHydraulicModelPropertyByName(self, hydraulicModelName: str) -> str:
        _projectId_ = self._projectId
        hydraulicModelName_ = hydraulicModelName
        request = ModelService.getCustomHydraulicModelPropertyByNameRequest(_projectId=_projectId_, hydraulicModelName=hydraulicModelName_)
        result_ = self._client.callFunction(self._ModelService.getCustomHydraulicModelPropertyByName, request)
        result = result_.result
        return result
    
    def getAllBoltProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllBoltPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllBoltProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllBeamProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllBeamPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllBeamProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllLinerProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllLinerPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllLinerProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllJointProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllJointPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllJointProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllLiningCompositionProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllLiningCompositionPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllLiningCompositionProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllPileProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllPilePropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllPileProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllMaterialProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllMaterialPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllMaterialProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllWaterByLocationProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllWaterByLocationPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllWaterByLocationProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllWaterGridProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllWaterGridPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllWaterGridProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllCustomHydraulicModelProperties(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllCustomHydraulicModelPropertiesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllCustomHydraulicModelProperties, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllExternalVolumes(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllExternalVolumesRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllExternalVolumes, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllBoltPropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllBoltPropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllBoltPropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllBeamPropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllBeamPropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllBeamPropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllLinerPropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllLinerPropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllLinerPropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllJointPropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllJointPropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllJointPropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllLiningCompositionPropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllLiningCompositionPropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllLiningCompositionPropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllPilePropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllPilePropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllPilePropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getAllMaterialPropertiesInUse(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getAllMaterialPropertiesInUseRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getAllMaterialPropertiesInUse, request)
        result = [obj for obj in result_.result]
        return result
    
    def getBoltPropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getBoltPropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getBoltPropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def getBeamPropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getBeamPropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getBeamPropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def getLinerPropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getLinerPropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getLinerPropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def getJointPropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getJointPropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getJointPropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def getLiningCompositionPropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getLiningCompositionPropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getLiningCompositionPropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def getPilePropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getPilePropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getPilePropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def getMaterialPropertiesInUseByStage(self, _stageNum: int) -> list[str]:
        _projectId_ = self._projectId
        _stageNum_ = _stageNum
        request = ModelService.getMaterialPropertiesInUseByStageRequest(_projectId=_projectId_, _stageNum=_stageNum_)
        result_ = self._client.callFunction(self._ModelService.getMaterialPropertiesInUseByStage, request)
        result = [obj for obj in result_.result]
        return result
    
    def createNewBoltProperty(self, boltName: str) -> None:
        _projectId_ = self._projectId
        boltName_ = boltName
        request = ModelService.createNewBoltPropertyRequest(_projectId=_projectId_, boltName=boltName_)
        self._client.callFunction(self._ModelService.createNewBoltProperty, request)
    
    def deleteBoltProperty(self, boltName: str) -> None:
        _projectId_ = self._projectId
        boltName_ = boltName
        request = ModelService.deleteBoltPropertyRequest(_projectId=_projectId_, boltName=boltName_)
        self._client.callFunction(self._ModelService.deleteBoltProperty, request)
    
    def createNewBeamProperty(self, beamName: str) -> None:
        _projectId_ = self._projectId
        beamName_ = beamName
        request = ModelService.createNewBeamPropertyRequest(_projectId=_projectId_, beamName=beamName_)
        self._client.callFunction(self._ModelService.createNewBeamProperty, request)
    
    def deleteBeamProperty(self, beamName: str) -> None:
        _projectId_ = self._projectId
        beamName_ = beamName
        request = ModelService.deleteBeamPropertyRequest(_projectId=_projectId_, beamName=beamName_)
        self._client.callFunction(self._ModelService.deleteBeamProperty, request)
    
    def createNewJointProperty(self, jointName: str) -> None:
        _projectId_ = self._projectId
        jointName_ = jointName
        request = ModelService.createNewJointPropertyRequest(_projectId=_projectId_, jointName=jointName_)
        self._client.callFunction(self._ModelService.createNewJointProperty, request)
    
    def deleteJointProperty(self, jointName: str) -> None:
        _projectId_ = self._projectId
        jointName_ = jointName
        request = ModelService.deleteJointPropertyRequest(_projectId=_projectId_, jointName=jointName_)
        self._client.callFunction(self._ModelService.deleteJointProperty, request)
    
    def createNewLinerProperty(self, linerName: str) -> None:
        _projectId_ = self._projectId
        linerName_ = linerName
        request = ModelService.createNewLinerPropertyRequest(_projectId=_projectId_, linerName=linerName_)
        self._client.callFunction(self._ModelService.createNewLinerProperty, request)
    
    def deleteLinerProperty(self, linerName: str) -> None:
        _projectId_ = self._projectId
        linerName_ = linerName
        request = ModelService.deleteLinerPropertyRequest(_projectId=_projectId_, linerName=linerName_)
        self._client.callFunction(self._ModelService.deleteLinerProperty, request)
    
    def createNewLiningCompositionProperty(self, compositeLinerName: str) -> None:
        _projectId_ = self._projectId
        compositeLinerName_ = compositeLinerName
        request = ModelService.createNewLiningCompositionPropertyRequest(_projectId=_projectId_, compositeLinerName=compositeLinerName_)
        self._client.callFunction(self._ModelService.createNewLiningCompositionProperty, request)
    
    def deleteLiningCompositionProperty(self, compositeLinerName: str) -> None:
        _projectId_ = self._projectId
        compositeLinerName_ = compositeLinerName
        request = ModelService.deleteLiningCompositionPropertyRequest(_projectId=_projectId_, compositeLinerName=compositeLinerName_)
        self._client.callFunction(self._ModelService.deleteLiningCompositionProperty, request)
    
    def createNewPileProperty(self, pileName: str) -> None:
        _projectId_ = self._projectId
        pileName_ = pileName
        request = ModelService.createNewPilePropertyRequest(_projectId=_projectId_, pileName=pileName_)
        self._client.callFunction(self._ModelService.createNewPileProperty, request)
    
    def deletePileProperty(self, pileName: str) -> None:
        _projectId_ = self._projectId
        pileName_ = pileName
        request = ModelService.deletePilePropertyRequest(_projectId=_projectId_, pileName=pileName_)
        self._client.callFunction(self._ModelService.deletePileProperty, request)
    
    def createNewMaterialProperty(self, materialName: str) -> None:
        _projectId_ = self._projectId
        materialName_ = materialName
        request = ModelService.createNewMaterialPropertyRequest(_projectId=_projectId_, materialName=materialName_)
        self._client.callFunction(self._ModelService.createNewMaterialProperty, request)
    
    def deleteMaterialProperty(self, materialName: str) -> None:
        _projectId_ = self._projectId
        materialName_ = materialName
        request = ModelService.deleteMaterialPropertyRequest(_projectId=_projectId_, materialName=materialName_)
        self._client.callFunction(self._ModelService.deleteMaterialProperty, request)
    
    def createNewWaterByLocationProperty(self, waterSurfaceName: str) -> None:
        _projectId_ = self._projectId
        waterSurfaceName_ = waterSurfaceName
        request = ModelService.createNewWaterByLocationPropertyRequest(_projectId=_projectId_, waterSurfaceName=waterSurfaceName_)
        self._client.callFunction(self._ModelService.createNewWaterByLocationProperty, request)
    
    def deleteWaterByLocationProperty(self, waterSurfaceName: str) -> None:
        _projectId_ = self._projectId
        waterSurfaceName_ = waterSurfaceName
        request = ModelService.deleteWaterByLocationPropertyRequest(_projectId=_projectId_, waterSurfaceName=waterSurfaceName_)
        self._client.callFunction(self._ModelService.deleteWaterByLocationProperty, request)
    
    def createNewWaterGridProperty(self, waterGridName: str) -> None:
        _projectId_ = self._projectId
        waterGridName_ = waterGridName
        request = ModelService.createNewWaterGridPropertyRequest(_projectId=_projectId_, waterGridName=waterGridName_)
        self._client.callFunction(self._ModelService.createNewWaterGridProperty, request)
    
    def deleteWaterGridProperty(self, waterGridName: str) -> None:
        _projectId_ = self._projectId
        waterGridName_ = waterGridName
        request = ModelService.deleteWaterGridPropertyRequest(_projectId=_projectId_, waterGridName=waterGridName_)
        self._client.callFunction(self._ModelService.deleteWaterGridProperty, request)
    
    def getDiscreteFunctions(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getDiscreteFunctionsRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getDiscreteFunctions, request)
        result = [obj for obj in result_.result]
        return result
    
    def getShearNormalFunctions(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getShearNormalFunctionsRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getShearNormalFunctions, request)
        result = [obj for obj in result_.result]
        return result
    
    def getGeneralizedAnisotropicFunctions(self) -> list[str]:
        _projectId_ = self._projectId
        request = ModelService.getGeneralizedAnisotropicFunctionsRequest(_projectId=_projectId_)
        result_ = self._client.callFunction(self._ModelService.getGeneralizedAnisotropicFunctions, request)
        result = [obj for obj in result_.result]
        return result
    
    def createNewDiscreteFunction(self, discreteFunctionName: str) -> None:
        _projectId_ = self._projectId
        discreteFunctionName_ = discreteFunctionName
        request = ModelService.createNewDiscreteFunctionRequest(_projectId=_projectId_, discreteFunctionName=discreteFunctionName_)
        self._client.callFunction(self._ModelService.createNewDiscreteFunction, request)
    
    def deleteDiscreteFunction(self, discreteFunctionName: str) -> None:
        _projectId_ = self._projectId
        discreteFunctionName_ = discreteFunctionName
        request = ModelService.deleteDiscreteFunctionRequest(_projectId=_projectId_, discreteFunctionName=discreteFunctionName_)
        self._client.callFunction(self._ModelService.deleteDiscreteFunction, request)
    
    def createNewShearNormalFunction(self, shearNormalFunctionName: str) -> None:
        _projectId_ = self._projectId
        shearNormalFunctionName_ = shearNormalFunctionName
        request = ModelService.createNewShearNormalFunctionRequest(_projectId=_projectId_, shearNormalFunctionName=shearNormalFunctionName_)
        self._client.callFunction(self._ModelService.createNewShearNormalFunction, request)
    
    def deleteShearNormalFunction(self, shearNormalFunctionName: str) -> None:
        _projectId_ = self._projectId
        shearNormalFunctionName_ = shearNormalFunctionName
        request = ModelService.deleteShearNormalFunctionRequest(_projectId=_projectId_, shearNormalFunctionName=shearNormalFunctionName_)
        self._client.callFunction(self._ModelService.deleteShearNormalFunction, request)
    
    def createNewGeneralizedAnisotropicFunction(self, generalizedAnisotropicFunctionName: str) -> None:
        _projectId_ = self._projectId
        generalizedAnisotropicFunctionName_ = generalizedAnisotropicFunctionName
        request = ModelService.createNewGeneralizedAnisotropicFunctionRequest(_projectId=_projectId_, generalizedAnisotropicFunctionName=generalizedAnisotropicFunctionName_)
        self._client.callFunction(self._ModelService.createNewGeneralizedAnisotropicFunction, request)
    
    def deleteGeneralizedAnisotropicFunction(self, generalizedAnisotropicFunctionName: str) -> None:
        _projectId_ = self._projectId
        generalizedAnisotropicFunctionName_ = generalizedAnisotropicFunctionName
        request = ModelService.deleteGeneralizedAnisotropicFunctionRequest(_projectId=_projectId_, generalizedAnisotropicFunctionName=generalizedAnisotropicFunctionName_)
        self._client.callFunction(self._ModelService.deleteGeneralizedAnisotropicFunction, request)
    
    def createNewCustomHydraulicModel(self, customHydraulicModelFunctionName: str) -> None:
        _projectId_ = self._projectId
        customHydraulicModelFunctionName_ = customHydraulicModelFunctionName
        request = ModelService.createNewCustomHydraulicModelRequest(_projectId=_projectId_, customHydraulicModelFunctionName=customHydraulicModelFunctionName_)
        self._client.callFunction(self._ModelService.createNewCustomHydraulicModel, request)
    
    def deleteCustomHydraulicModel(self, hydraulicModelName: str) -> None:
        _projectId_ = self._projectId
        hydraulicModelName_ = hydraulicModelName
        request = ModelService.deleteCustomHydraulicModelRequest(_projectId=_projectId_, hydraulicModelName=hydraulicModelName_)
        self._client.callFunction(self._ModelService.deleteCustomHydraulicModel, request)
    
def ModelBase2ModelModelBase(a: ModelBase) -> ModelService.ModelBase:
    result = ModelService.ModelBase(_projectId=a._projectId)
    return result

def ModelModelBase2ModelBase(client: Client, a: ModelService.ModelBase) -> ModelBase:
    result = ModelBase(client, a._projectId)
    return result


################ Code below this line will not be overridden ################
from rs3.projectSettings.ProjectSettings import ProjectSettings
from rs3.loadings.Loadings import Loadings
from rs3.mesh.Mesh import Mesh
from rs3.properties.bolt.Bolt import BoltProperty
from rs3.properties.beam.Beam import BeamProperty
from rs3.properties.liner.Liner import LinerProperty
from rs3.properties.joint.Joint import JointProperty
from rs3.properties.liningComposition.LiningComposition import LiningCompositionProperty
from rs3.properties.pile.Pile import PileProperty
from rs3.properties.material.Material import MaterialProperty
from rs3.properties.groundwater.WaterByLocation import WaterByLocationProperty
from rs3.properties.groundwater.WaterGrid import WaterGridProperty
from rs3.ExternalVolume import ExternalVolume
from rs3.properties.DiscreteFunction import DiscreteFunction
from rs3.properties.ShearNormalFunction import ShearNormalFunction
from rs3.properties.GeneralizedAnisotropicFunction import GeneralizedAnisotropicFunction
from rs3.properties.CustomHydraulicModel import CustomHydraulicModel
from rs3.Restraints import Restraints
from rs3.Selection import Selection
from rs3.Compute import Compute
from rs3.results.Results import Results
from rs3.ModelEnums import *

class Model(ModelBase):
    """
    Examples:
        See :ref:`model_example`.
    """    
    def __init__(self, client: Client, projectId: str):
        super().__init__(client, projectId)
        self.ProjectSettings = ProjectSettings(client, projectId)
        self.Selection = Selection(client, projectId)
        self.Loadings = Loadings(client, projectId)
        self.Restraints = Restraints(client, projectId)
        self.Mesh = Mesh(client, projectId)
        self.Results = Results(client, projectId)
        self.Compute = Compute(client, projectId)

    @property
    def results(self):
        self.Results.querySRFValues()
        return self.Results

    def setActiveStageByName(self, stageName: str) -> None:
        """
        Set the active stage in the RS3 model by its name.

        Parameters
        ----------
        stageName : str
            The exact name of the stage to activate.
        """
        super().setActiveStageByName(stageName)
    
    def getActiveStageName(self) -> str:
        """
        Retrieve the name of the currently active stage in the RS3 model.

        Returns
        -------
        str
            The name of the active stage.
        """
        stageName = super().getActiveStageName()
        return stageName
    
    def setActiveStage(self, stageNum: int) -> None:
        """
        Set the active stage in the RS3 model by its index.

        Parameters
        ----------
        stageNum : int
            The index of the absolute stage or relative stage (if reference stage is set) to activate. Counting starts at 1. (i.e., the first stage is 1, the second is 2, etc.).
        """
        super().setActiveStage(stageNum)
    
    def getActiveStage(self) -> int:
        """
        Retrieve the index of the currently active stage in the RS3 model.

        Returns
        -------
        int
            The index of absolute stage or relative stage (if reference stage is set) is active. Counting starts at 1. (i.e., the first stage is 1, the second is 2, etc.).
        """
        stageIndex = super().getActiveStage()
        return stageIndex
        
    def getBoltPropertyByName(self, boltName) -> BoltProperty:
        boltProp = super().getBoltPropertyByName(boltName)
        return BoltProperty(self._client, boltProp)
    
    def getBeamPropertyByName(self, beamName) -> BeamProperty:
        beamProp = super().getBeamPropertyByName(beamName)
        return BeamProperty(self._client, beamProp)
    
    def getLinerPropertyByName(self, linerName) -> LinerProperty:
        linerProp = super().getLinerPropertyByName(linerName)
        return LinerProperty(self._client, linerProp)
    
    def getJointPropertyByName(self, linerName) -> JointProperty:
        jointProp = super().getJointPropertyByName(linerName)
        return JointProperty(self._client, jointProp)
    
    def getPilePropertyByName(self, pileName) -> PileProperty:
        pileProp = super().getPilePropertyByName(pileName)
        return PileProperty(self._client, pileProp)
    
    def getLiningCompositionPropertyByName(self, liningCompositionName) -> LiningCompositionProperty:
        liningCompositionProp = super().getLiningCompositionPropertyByName(liningCompositionName)
        return LiningCompositionProperty(self._client, liningCompositionProp)
    
    def getCustomHydraulicModelPropertyByName(self, customHydraulicModelName) -> CustomHydraulicModel:
        customHydraulicModelNameProp = super().getCustomHydraulicModelPropertyByName(customHydraulicModelName)
        return CustomHydraulicModel(self._client, customHydraulicModelNameProp, self._projectId)

    def getMaterialPropertyByName(self, materialName) -> MaterialProperty:
        materialProp = super().getMaterialPropertyByName(materialName)
        return MaterialProperty(self._client, materialProp)
    
    def getWaterByLocationPropertyByName(self, waterSurfaceName) -> WaterByLocationProperty:
        waterSurfaceProp = super().getWaterByLocationPropertyByName(waterSurfaceName)
        return WaterByLocationProperty(self._client, waterSurfaceProp, self._projectId)
    
    def getWaterGridPropertyByName(self, waterGridName) -> WaterGridProperty:
        waterGridProp = super().getWaterGridPropertyByName(waterGridName)
        return WaterGridProperty(self._client, waterGridProp, self._projectId)
    
    def getExternalVolumeByName(self, externalVolumeName) -> ExternalVolume:
        externalVolumeProp = super().getExternalVolumeByName(externalVolumeName)
        return ExternalVolume(self._client, externalVolumeProp)
    
    def getDiscreteFunctionByName(self, discreteFunctionName) -> DiscreteFunction:
        discreteFunctionProp = super().getDiscreteFunctionByName(discreteFunctionName)
        return DiscreteFunction(self._client, discreteFunctionProp)
    
    def getShearNormalFunctionByName(self, shearNormalFunctionName) -> ShearNormalFunction:
        shearNormalFunctionProp = super().getShearNormalFunctionByName(shearNormalFunctionName)
        return ShearNormalFunction(self._client, shearNormalFunctionProp)
    
    def getGeneralizedAnisotropicFunctionByName(self, generalizedAnisotropicFunctionName) -> GeneralizedAnisotropicFunction:
        generalizedAnisotropicFunctionProp = super().getGeneralizedAnisotropicFunctionByName(generalizedAnisotropicFunctionName)
        return GeneralizedAnisotropicFunction(self._client, generalizedAnisotropicFunctionProp, self._projectId)

    def getAllBoltProperties(self) -> list[BoltProperty]:
        boltProps = super().getAllBoltProperties()
        return [BoltProperty(self._client, obj) for obj in boltProps]

    def getAllBeamProperties(self) -> list[BeamProperty]:
        beamProps = super().getAllBeamProperties()
        return [BeamProperty(self._client, obj) for obj in beamProps]
    
    def getAllLinerProperties(self) -> list[LinerProperty]:
        linerProps = super().getAllLinerProperties()
        return [LinerProperty(self._client, obj) for obj in linerProps]
       
    def getAllJointProperties(self) -> list[JointProperty]:
        jointProps = super().getAllJointProperties()
        return [JointProperty(self._client, obj) for obj in jointProps]
    
    def getAllLiningCompositionProperties(self) -> list[LiningCompositionProperty]:
        liningCompositionProps = super().getAllLiningCompositionProperties()
        return [LiningCompositionProperty(self._client, obj) for obj in liningCompositionProps]
    
    def getAllPileProperties(self) -> list[PileProperty]:
        pileProp = super().getAllPileProperties()
        return [PileProperty(self._client, obj) for obj in pileProp]

    def getAllMaterialProperties(self) -> list[MaterialProperty]:
        materialProps = super().getAllMaterialProperties()
        return [MaterialProperty(self._client, obj) for obj in materialProps]
    
    def getAllWaterByLocationProperties(self) -> list[WaterByLocationProperty]:
        waterByLocationProps = super().getAllWaterByLocationProperties()
        return [WaterByLocationProperty(self._client, obj, self._projectId) for obj in waterByLocationProps]
    
    def getAllWaterGridProperties(self) -> list[WaterGridProperty]:
        waterGridProps = super().getAllWaterGridProperties()
        return [WaterGridProperty(self._client, obj, self._projectId) for obj in waterGridProps]
    
    def getAllCustomHydraulicModelProperties(self) -> list[CustomHydraulicModel]:
        customHydraulicModelProps = super().getAllCustomHydraulicModelProperties()
        return [CustomHydraulicModel(self._client, obj, self._projectId) for obj in customHydraulicModelProps]
    
    def getAllExternalVolumes(self) -> list[ExternalVolume]:
        externalVolumesProps = super().getAllExternalVolumes()
        return [ExternalVolume(self._client, obj) for obj in externalVolumesProps]
    
    def getAllBoltPropertiesInUse(self) -> list[BoltProperty]:
        boltProps = super().getAllBoltPropertiesInUse()
        return [BoltProperty(self._client, obj) for obj in boltProps]
    
    def getAllBeamPropertiesInUse(self) -> list[BeamProperty]:
        beamProps = super().getAllBeamPropertiesInUse()
        return [BeamProperty(self._client, obj) for obj in beamProps]
    
    def getAllLinerPropertiesInUse(self) -> list[LinerProperty]:
        linerProps = super().getAllLinerPropertiesInUse()
        return [LinerProperty(self._client, obj) for obj in linerProps]
    
    def getAllJointPropertiesInUse(self) -> list[JointProperty]:
        jointProps = super().getAllJointPropertiesInUse()
        return [JointProperty(self._client, obj) for obj in jointProps]
    
    def getAllPilePropertiesInUse(self) -> list[PileProperty]:
        pileProps = super().getAllPilePropertiesInUse()
        return [PileProperty(self._client, obj) for obj in pileProps]
    
    def getAllLiningCompositionPropertiesInUse(self) -> list[LiningCompositionProperty]:
        liningCompositionProps = super().getAllLiningCompositionPropertiesInUse()
        return [LiningCompositionProperty(self._client, obj) for obj in liningCompositionProps]
    
    def getAllMaterialPropertiesInUse(self) -> list[MaterialProperty]:
        materialProps = super().getAllMaterialPropertiesInUse()
        return [MaterialProperty(self._client, obj) for obj in materialProps]
    
    def getBoltPropertiesInUseByStage(self, stageNum : int) -> list[BoltProperty]:
        boltProps = super().getBoltPropertiesInUseByStage(stageNum)
        return [BoltProperty(self._client, obj) for obj in boltProps]
    
    def getBeamPropertiesInUseByStage(self, stageNum : int) -> list[BeamProperty]:
        beamProps = super().getBeamPropertiesInUseByStage(stageNum)
        return [BeamProperty(self._client, obj) for obj in beamProps]
    
    def getLinerPropertiesInUseByStage(self, stageNum : int) -> list[LinerProperty]:
        linerProps = super().getLinerPropertiesInUseByStage(stageNum)
        return [LinerProperty(self._client, obj) for obj in linerProps]
    
    def getJointPropertiesInUseByStage(self, stageNum : int) -> list[JointProperty]:
        jointProps = super().getJointPropertiesInUseByStage(stageNum)
        return [JointProperty(self._client, obj) for obj in jointProps]
    
    def getPilePropertiesInUseByStage(self, stageNum : int) -> list[PileProperty]:
        pileProps = super().getPilePropertiesInUseByStage(stageNum)
        return [PileProperty(self._client, obj) for obj in pileProps]
    
    def getLiningCompositionPropertiesInUseByStage(self, stageNum : int) -> list[LiningCompositionProperty]:
        liningCompositionProps = super().getLiningCompositionPropertiesInUseByStage(stageNum)
        return [LiningCompositionProperty(self._client, obj) for obj in liningCompositionProps]
    
    def getMaterialPropertiesInUseByStage(self, stageNum : int) -> list[MaterialProperty]:
        materialProps = super().getMaterialPropertiesInUseByStage(stageNum)
        return [MaterialProperty(self._client, obj) for obj in materialProps]
    
    def getDiscreteFunctions(self) -> list[DiscreteFunction]:
        discreteFunctionProps = super().getDiscreteFunctions()
        return [DiscreteFunction(self._client, obj) for obj in discreteFunctionProps]
    
    def getShearNormalFunctions(self) -> list[ShearNormalFunction]:
        shearNormalFunctionProps = super().getShearNormalFunctions()
        return [ShearNormalFunction(self._client, obj) for obj in shearNormalFunctionProps]
    
    def getGeneralizedAnisotropicFunctions(self) -> list[GeneralizedAnisotropicFunction]:
        generalizedAnisotropicFunctionProps = super().getGeneralizedAnisotropicFunctions()
        return [GeneralizedAnisotropicFunction(self._client, obj, self._projectId) for obj in generalizedAnisotropicFunctionProps]
