from enum import Enum

# units
class UnitSystemType(Enum):
    METRIC_MPA = "RFC_METRIC_MPA"
    METRIC_KPA = "RFC_METRIC_KPA"
    METRIC_TONNES = "RFC_METRIC_TONNES"
    IMPERIAL_TONS = "RFC_IMPERIAL_TONS"
    IMPERIAL_KSF = "RFC_IMPERIAL_KSF"
    IMPERIAL_PSF = "RFC_IMPERIAL_PSF"

class TimeUnitsType(Enum):
    SECONDS = "SECONDS"
    MINUTES = "MINUTES"
    HOURS = "HOURS"
    DAYS = "DAYS"
    MONTHS = "MONTHS"
    YEARS = "YEARS"
    
class PermeabilityUnitsType(Enum):
    FEET_SECONDS = "FEET_SECONDS"
    FEET_MINUTES = "FEET_MINUTES"
    FEET_HOURS = "FEET_HOURS"
    FEET_DAYS = "FEET_DAYS"
    FEET_MONTHS = "FEET_MONTHS"
    FEET_YEARS = "FEET_YEARS"
    INCHES_SECOND = "INCHES_SECOND"
    INCHES_MINUTES = "INCHES_MINUTES"
    INCHES_HOURS = "INCHES_HOURS"
    INCHES_DAYS = "INCHES_DAYS"
    INCHES_MONTHS = "INCHES_MONTHS"
    INCHES_YEARS = "INCHES_YEARS"
    METER_SECONDS = "METER_SECONDS"
    METER_MINUTES = "METER_MINUTES"
    METER_HOURS = "METER_HOURS"
    METER_DAYS = "METER_DAYS"
    METER_MONTHS = "METER_MONTHS"
    METER_YEARS = "METER_YEARS"
    CENTIMETER_SECONDS = "CENTIMETER_SECONDS"
    CENTIMETER_MINUTES = "CENTIMETER_MINUTES"
    CENTIMETER_HOURS = "CENTIMETER_HOURS"
    CENTIMETER_DAYS = "CENTIMETER_DAYS"
    CENTIMETER_MONTHS = "CENTIMETER_MONTHS"
    CENTIMETER_YEARS = "CENTIMETER_YEARS"
    MILLIMETER_SECONDS = "MILLIMETER_SECONDS"
    MILLIMETER_MINUTES = "MILLIMETER_MINUTES"
    MILLIMETER_HOURS = "MILLIMETER_HOURS"
    MILLIMETER_DAYS = "MILLIMETER_DAYS"
    MILLIMETER_MONTHS = "MILLIMETER_MONTHS"
    MILLIMETER_YEARS = "MILLIMETER_YEARS"

# Stages
class PWPMethod(Enum):
    GW_NONE = "GW_NONE"
    GW_SURFACES = "GW_SURFACES"
    GW_STEADYSTATE = "GW_STEADYSTATE"
    GW_TRANSIENT = "GW_TRANSIENT"

# Stress Analysis
class LoadStepType(Enum):
    LoadAuto = "LoadAuto"
    LoadFixed = "LoadFixed"
    LoadAdaptive = "LoadAdaptive"
    
class StressConvergenceCriteriaType(Enum):
    ABSOLUTE_ENERGY = "ABSOLUTE_ENERGY"
    ABSOLUTE_FORCE = "ABSOLUTE_FORCE"
    ABSOLUTE_FORCE_ENERGY = "ABSOLUTE_FORCE_ENERGY"

# Solver Options
class AnalysisType(Enum):
    UNCOUPLED = "UNCOUPLED"
    COUPLED_BIOT = "COUPLED_BIOT"

class SolverType(Enum):
    DIRECT_CPU = "DIRECT"
    ITERATIVE_CPU = "ITERATIVE"
    FGMRES_AMG_PRECONDITIONER_CPU = "FGMRES_AMG_PRECONDITIONER"
    FGMRESG_ILU_PRECONDITIONER_CPU = "FGMRESG_ILU_PRECONDITONER"
    DIRECT_GPU = "DIRECT_GPU"
    FGMRES_AMG_GPU = "FGMRES_AMG_GPU"
    AUTO = "AUTO"
    
# Groundwater
class GWLoadStepType(Enum):
    AUTO = "Auto"
    FIXED = "Fixed"
    
class TimeStepType(Enum):
    AUTO = "Auto"
    FIXED = "Fixed"
    
class GroundwaterMethodType(Enum):
    GW_NONE = "GW_NONE"
    GW_SURFACES = "GW_SURFACES"
    GW_STEADYSTATE = "GW_STEADYSTATE"
    GW_TRANSIENT = "GW_TRANSIENT"

# SSR
class SSRConvergenceType(Enum):
    ABSOLUTE_ENERGY = "ABSOLUTE_ENERGY"
    ABSOLUTE_FORCE = "ABSOLUTE_FORCE"
    ABSOLUTE_FORCE_ENERGY = "ABSOLUTE_FORCE_ENERGY"

# Dynamic
class TimeHistoryType(Enum):
    TIME_AUTO = "TimeAuto"
    NUM_TIME_STEPS = "NumTimeSteps"
