# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import BeamsResultsQueryService_pb2 as BeamsResultsQueryService__pb2
import ResultsQueryCommonMessage_pb2 as ResultsQueryCommonMessage__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in BeamsResultsQueryService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BeamResultsQueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryBeamNodalResults = channel.unary_stream(
                '/BeamsResultsQueryServiceDefinition.BeamResultsQueryService/QueryBeamNodalResults',
                request_serializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
                response_deserializer=ResultsQueryCommonMessage__pb2.StructuralNodeResultsResponseChunk.FromString,
                _registered_method=True)
        self.QueryBeamElementResults = channel.unary_stream(
                '/BeamsResultsQueryServiceDefinition.BeamResultsQueryService/QueryBeamElementResults',
                request_serializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
                response_deserializer=BeamsResultsQueryService__pb2.BeamElementResultsResponseChunk.FromString,
                _registered_method=True)


class BeamResultsQueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryBeamNodalResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBeamElementResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeamResultsQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryBeamNodalResults': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryBeamNodalResults,
                    request_deserializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.FromString,
                    response_serializer=ResultsQueryCommonMessage__pb2.StructuralNodeResultsResponseChunk.SerializeToString,
            ),
            'QueryBeamElementResults': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryBeamElementResults,
                    request_deserializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.FromString,
                    response_serializer=BeamsResultsQueryService__pb2.BeamElementResultsResponseChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BeamsResultsQueryServiceDefinition.BeamResultsQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BeamsResultsQueryServiceDefinition.BeamResultsQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BeamResultsQueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryBeamNodalResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/BeamsResultsQueryServiceDefinition.BeamResultsQueryService/QueryBeamNodalResults',
            ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
            ResultsQueryCommonMessage__pb2.StructuralNodeResultsResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBeamElementResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/BeamsResultsQueryServiceDefinition.BeamResultsQueryService/QueryBeamElementResults',
            ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
            BeamsResultsQueryService__pb2.BeamElementResultsResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
