# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CompositeLinerService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'CompositeLinerService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CommonMessages_pb2 as CommonMessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43ompositeLinerService.proto\x12\x1f\x43ompositeLinerServiceDefinition\x1a\x14\x43ommonMessages.proto2\xc7\x01\n\x15\x43ompositeLinerService\x12V\n\x0bSetProperty\x12\".CommonMessages.SetPropertyRequest\x1a#.CommonMessages.SetPropertyResponse\x12V\n\x0bGetProperty\x12\".CommonMessages.GetPropertyRequest\x1a#.CommonMessages.GetPropertyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CompositeLinerService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPOSITELINERSERVICE']._serialized_start=87
  _globals['_COMPOSITELINERSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
