# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CommonMessages_pb2 as CommonMessages__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in CompositeLinerService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompositeLinerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProperty = channel.unary_unary(
                '/CompositeLinerServiceDefinition.CompositeLinerService/SetProperty',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/CompositeLinerServiceDefinition.CompositeLinerService/GetProperty',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)


class CompositeLinerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompositeLinerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CompositeLinerServiceDefinition.CompositeLinerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CompositeLinerServiceDefinition.CompositeLinerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompositeLinerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CompositeLinerServiceDefinition.CompositeLinerService/SetProperty',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CompositeLinerServiceDefinition.CompositeLinerService/GetProperty',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
