# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GaussPointFailureMessage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'GaussPointFailureMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CommonMessages_pb2 as CommonMessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGaussPointFailureMessage.proto\x12\x18GaussPointFailureMessage\x1a\x14\x43ommonMessages.proto\"S\n\x11GaussPointFailure\x12)\n\x08location\x18\x01 \x01(\x0b\x32\x17.CommonMessages.Point3D\x12\x13\n\x0b\x66\x61ilureType\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GaussPointFailureMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAUSSPOINTFAILURE']._serialized_start=82
  _globals['_GAUSSPOINTFAILURE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
