# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CommonMessages_pb2 as CommonMessages__pb2
import HydraulicStageFactorService_pb2 as HydraulicStageFactorService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in HydraulicStageFactorService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HydraulicStageFactorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetStageFactorProperty = channel.unary_unary(
                '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/SetStageFactorProperty',
                request_serializer=CommonMessages__pb2.SetStageFactorPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetStageFactorPropertyResponse.FromString,
                _registered_method=True)
        self.GetStageFactorProperty = channel.unary_unary(
                '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/GetStageFactorProperty',
                request_serializer=CommonMessages__pb2.GetStageFactorPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetStageFactorPropertyResponse.FromString,
                _registered_method=True)
        self.SetInitialWaterCondition = channel.unary_unary(
                '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/SetInitialWaterCondition',
                request_serializer=HydraulicStageFactorService__pb2.SetInitialWaterConditionRequest.SerializeToString,
                response_deserializer=HydraulicStageFactorService__pb2.SetInitialWaterConditionResponse.FromString,
                _registered_method=True)
        self.GetInitialWaterCondition = channel.unary_unary(
                '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/GetInitialWaterCondition',
                request_serializer=HydraulicStageFactorService__pb2.GetInitialWaterConditionRequest.SerializeToString,
                response_deserializer=HydraulicStageFactorService__pb2.GetInitialWaterConditionResponse.FromString,
                _registered_method=True)


class HydraulicStageFactorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetStageFactorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStageFactorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInitialWaterCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInitialWaterCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HydraulicStageFactorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetStageFactorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStageFactorProperty,
                    request_deserializer=CommonMessages__pb2.SetStageFactorPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetStageFactorPropertyResponse.SerializeToString,
            ),
            'GetStageFactorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStageFactorProperty,
                    request_deserializer=CommonMessages__pb2.GetStageFactorPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetStageFactorPropertyResponse.SerializeToString,
            ),
            'SetInitialWaterCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInitialWaterCondition,
                    request_deserializer=HydraulicStageFactorService__pb2.SetInitialWaterConditionRequest.FromString,
                    response_serializer=HydraulicStageFactorService__pb2.SetInitialWaterConditionResponse.SerializeToString,
            ),
            'GetInitialWaterCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInitialWaterCondition,
                    request_deserializer=HydraulicStageFactorService__pb2.GetInitialWaterConditionRequest.FromString,
                    response_serializer=HydraulicStageFactorService__pb2.GetInitialWaterConditionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HydraulicStageFactorServiceDefinition.HydraulicStageFactorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('HydraulicStageFactorServiceDefinition.HydraulicStageFactorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HydraulicStageFactorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetStageFactorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/SetStageFactorProperty',
            CommonMessages__pb2.SetStageFactorPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetStageFactorPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStageFactorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/GetStageFactorProperty',
            CommonMessages__pb2.GetStageFactorPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetStageFactorPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInitialWaterCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/SetInitialWaterCondition',
            HydraulicStageFactorService__pb2.SetInitialWaterConditionRequest.SerializeToString,
            HydraulicStageFactorService__pb2.SetInitialWaterConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInitialWaterCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HydraulicStageFactorServiceDefinition.HydraulicStageFactorService/GetInitialWaterCondition',
            HydraulicStageFactorService__pb2.GetInitialWaterConditionRequest.SerializeToString,
            HydraulicStageFactorService__pb2.GetInitialWaterConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
