# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CommonMessages_pb2 as CommonMessages__pb2
import JointDataService_pb2 as JointDataService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in JointDataService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JointDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProperty = channel.unary_unary(
                '/JointDataServiceDefinition.JointDataService/SetProperty',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/JointDataServiceDefinition.JointDataService/GetProperty',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetColorProperty = channel.unary_unary(
                '/JointDataServiceDefinition.JointDataService/SetColorProperty',
                request_serializer=CommonMessages__pb2.SetColorRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetColorResponse.FromString,
                _registered_method=True)
        self.GetColorProperty = channel.unary_unary(
                '/JointDataServiceDefinition.JointDataService/GetColorProperty',
                request_serializer=CommonMessages__pb2.GetColorRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetColorResponse.FromString,
                _registered_method=True)
        self.SetPiezoToUse = channel.unary_unary(
                '/JointDataServiceDefinition.JointDataService/SetPiezoToUse',
                request_serializer=JointDataService__pb2.SetPiezoToUseRequest.SerializeToString,
                response_deserializer=JointDataService__pb2.SetPiezoToUseResponse.FromString,
                _registered_method=True)
        self.GetPiezoToUse = channel.unary_unary(
                '/JointDataServiceDefinition.JointDataService/GetPiezoToUse',
                request_serializer=JointDataService__pb2.GetPiezoToUseRequest.SerializeToString,
                response_deserializer=JointDataService__pb2.GetPiezoToUseResponse.FromString,
                _registered_method=True)


class JointDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetColorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPiezoToUse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPiezoToUse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JointDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetColorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetColorProperty,
                    request_deserializer=CommonMessages__pb2.SetColorRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetColorResponse.SerializeToString,
            ),
            'GetColorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColorProperty,
                    request_deserializer=CommonMessages__pb2.GetColorRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetColorResponse.SerializeToString,
            ),
            'SetPiezoToUse': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPiezoToUse,
                    request_deserializer=JointDataService__pb2.SetPiezoToUseRequest.FromString,
                    response_serializer=JointDataService__pb2.SetPiezoToUseResponse.SerializeToString,
            ),
            'GetPiezoToUse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPiezoToUse,
                    request_deserializer=JointDataService__pb2.GetPiezoToUseRequest.FromString,
                    response_serializer=JointDataService__pb2.GetPiezoToUseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JointDataServiceDefinition.JointDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('JointDataServiceDefinition.JointDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JointDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/JointDataServiceDefinition.JointDataService/SetProperty',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/JointDataServiceDefinition.JointDataService/GetProperty',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetColorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/JointDataServiceDefinition.JointDataService/SetColorProperty',
            CommonMessages__pb2.SetColorRequest.SerializeToString,
            CommonMessages__pb2.SetColorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetColorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/JointDataServiceDefinition.JointDataService/GetColorProperty',
            CommonMessages__pb2.GetColorRequest.SerializeToString,
            CommonMessages__pb2.GetColorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPiezoToUse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/JointDataServiceDefinition.JointDataService/SetPiezoToUse',
            JointDataService__pb2.SetPiezoToUseRequest.SerializeToString,
            JointDataService__pb2.SetPiezoToUseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPiezoToUse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/JointDataServiceDefinition.JointDataService/GetPiezoToUse',
            JointDataService__pb2.GetPiezoToUseRequest.SerializeToString,
            JointDataService__pb2.GetPiezoToUseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
