# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LinerStageFactorService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'LinerStageFactorService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CommonMessages_pb2 as CommonMessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dLinerStageFactorService.proto\x12!LinerStageFactorServiceDefinition\x1a\x14\x43ommonMessages.proto2\x8b\x02\n\x17LinerStageFactorService\x12w\n\x16SetStageFactorProperty\x12-.CommonMessages.SetStageFactorPropertyRequest\x1a..CommonMessages.SetStageFactorPropertyResponse\x12w\n\x16GetStageFactorProperty\x12-.CommonMessages.GetStageFactorPropertyRequest\x1a..CommonMessages.GetStageFactorPropertyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LinerStageFactorService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINERSTAGEFACTORSERVICE']._serialized_start=91
  _globals['_LINERSTAGEFACTORSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
