# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MaterialJointStageFactorService_pb2 as MaterialJointStageFactorService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MaterialJointStageFactorService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaterialJointStageFactorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetStageFactorProperty = channel.unary_unary(
                '/MaterialJointStageFactorServiceDefinition.MaterialJointStageFactorService/SetStageFactorProperty',
                request_serializer=MaterialJointStageFactorService__pb2.SetMaterialJointStageFactorPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointStageFactorService__pb2.SetMaterialJointStageFactorPropertyResponse.FromString,
                _registered_method=True)
        self.GetStageFactorProperty = channel.unary_unary(
                '/MaterialJointStageFactorServiceDefinition.MaterialJointStageFactorService/GetStageFactorProperty',
                request_serializer=MaterialJointStageFactorService__pb2.GetMaterialJointStageFactorPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointStageFactorService__pb2.GetMaterialJointStageFactorPropertyResponse.FromString,
                _registered_method=True)


class MaterialJointStageFactorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetStageFactorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStageFactorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaterialJointStageFactorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetStageFactorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStageFactorProperty,
                    request_deserializer=MaterialJointStageFactorService__pb2.SetMaterialJointStageFactorPropertyRequest.FromString,
                    response_serializer=MaterialJointStageFactorService__pb2.SetMaterialJointStageFactorPropertyResponse.SerializeToString,
            ),
            'GetStageFactorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStageFactorProperty,
                    request_deserializer=MaterialJointStageFactorService__pb2.GetMaterialJointStageFactorPropertyRequest.FromString,
                    response_serializer=MaterialJointStageFactorService__pb2.GetMaterialJointStageFactorPropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MaterialJointStageFactorServiceDefinition.MaterialJointStageFactorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MaterialJointStageFactorServiceDefinition.MaterialJointStageFactorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaterialJointStageFactorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetStageFactorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointStageFactorServiceDefinition.MaterialJointStageFactorService/SetStageFactorProperty',
            MaterialJointStageFactorService__pb2.SetMaterialJointStageFactorPropertyRequest.SerializeToString,
            MaterialJointStageFactorService__pb2.SetMaterialJointStageFactorPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStageFactorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointStageFactorServiceDefinition.MaterialJointStageFactorService/GetStageFactorProperty',
            MaterialJointStageFactorService__pb2.GetMaterialJointStageFactorPropertyRequest.SerializeToString,
            MaterialJointStageFactorService__pb2.GetMaterialJointStageFactorPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
