# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CommonMessages_pb2 as CommonMessages__pb2
import MaterialHydraulicModelService_pb2 as MaterialHydraulicModelService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MaterialHydraulicModelService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaterialHydraulicModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProperty = channel.unary_unary(
                '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/SetProperty',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/GetProperty',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetUserDefinedFunction = channel.unary_unary(
                '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/SetUserDefinedFunction',
                request_serializer=MaterialHydraulicModelService__pb2.SetUserDefinedFunctionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicModelService__pb2.SetUserDefinedFunctionResponse.FromString,
                _registered_method=True)
        self.GetUserDefinedFunction = channel.unary_unary(
                '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/GetUserDefinedFunction',
                request_serializer=MaterialHydraulicModelService__pb2.GetUserDefinedFunctionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicModelService__pb2.GetUserDefinedFunctionResponse.FromString,
                _registered_method=True)
        self.SetCustomHydraulicModelProperty = channel.unary_unary(
                '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/SetCustomHydraulicModelProperty',
                request_serializer=MaterialHydraulicModelService__pb2.SetCustomHydraulicModelPropertyRequest.SerializeToString,
                response_deserializer=MaterialHydraulicModelService__pb2.SetCustomHydraulicModelPropertyResponse.FromString,
                _registered_method=True)
        self.GetCustomHydraulicModelProperty = channel.unary_unary(
                '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/GetCustomHydraulicModelProperty',
                request_serializer=MaterialHydraulicModelService__pb2.GetCustomHydraulicModelPropertyRequest.SerializeToString,
                response_deserializer=MaterialHydraulicModelService__pb2.GetCustomHydraulicModelPropertyResponse.FromString,
                _registered_method=True)


class MaterialHydraulicModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserDefinedFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDefinedFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCustomHydraulicModelProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomHydraulicModelProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaterialHydraulicModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetUserDefinedFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserDefinedFunction,
                    request_deserializer=MaterialHydraulicModelService__pb2.SetUserDefinedFunctionRequest.FromString,
                    response_serializer=MaterialHydraulicModelService__pb2.SetUserDefinedFunctionResponse.SerializeToString,
            ),
            'GetUserDefinedFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDefinedFunction,
                    request_deserializer=MaterialHydraulicModelService__pb2.GetUserDefinedFunctionRequest.FromString,
                    response_serializer=MaterialHydraulicModelService__pb2.GetUserDefinedFunctionResponse.SerializeToString,
            ),
            'SetCustomHydraulicModelProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCustomHydraulicModelProperty,
                    request_deserializer=MaterialHydraulicModelService__pb2.SetCustomHydraulicModelPropertyRequest.FromString,
                    response_serializer=MaterialHydraulicModelService__pb2.SetCustomHydraulicModelPropertyResponse.SerializeToString,
            ),
            'GetCustomHydraulicModelProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomHydraulicModelProperty,
                    request_deserializer=MaterialHydraulicModelService__pb2.GetCustomHydraulicModelPropertyRequest.FromString,
                    response_serializer=MaterialHydraulicModelService__pb2.GetCustomHydraulicModelPropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaterialHydraulicModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/SetProperty',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/GetProperty',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUserDefinedFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/SetUserDefinedFunction',
            MaterialHydraulicModelService__pb2.SetUserDefinedFunctionRequest.SerializeToString,
            MaterialHydraulicModelService__pb2.SetUserDefinedFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDefinedFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/GetUserDefinedFunction',
            MaterialHydraulicModelService__pb2.GetUserDefinedFunctionRequest.SerializeToString,
            MaterialHydraulicModelService__pb2.GetUserDefinedFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCustomHydraulicModelProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/SetCustomHydraulicModelProperty',
            MaterialHydraulicModelService__pb2.SetCustomHydraulicModelPropertyRequest.SerializeToString,
            MaterialHydraulicModelService__pb2.SetCustomHydraulicModelPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomHydraulicModelProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicModelServiceDefinition.MaterialHydraulicModelService/GetCustomHydraulicModelProperty',
            MaterialHydraulicModelService__pb2.GetCustomHydraulicModelPropertyRequest.SerializeToString,
            MaterialHydraulicModelService__pb2.GetCustomHydraulicModelPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
