# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CommonMessages_pb2 as CommonMessages__pb2
import MaterialHydraulicDataService_pb2 as MaterialHydraulicDataService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MaterialHydraulicDataService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaterialHydraulicDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProperty = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetProperty',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetProperty',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetLinearDirection = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetLinearDirection',
                request_serializer=MaterialHydraulicDataService__pb2.SetLinearDirectionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.SetLinearDirectionResponse.FromString,
                _registered_method=True)
        self.GetLinearDirection = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetLinearDirection',
                request_serializer=MaterialHydraulicDataService__pb2.GetLinearDirectionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetLinearDirectionResponse.FromString,
                _registered_method=True)
        self.SetInitialWaterCondition = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetInitialWaterCondition',
                request_serializer=MaterialHydraulicDataService__pb2.SetInitialWaterConditionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.SetInitialWaterConditionResponse.FromString,
                _registered_method=True)
        self.GetInitialWaterCondition = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetInitialWaterCondition',
                request_serializer=MaterialHydraulicDataService__pb2.GetInitialWaterConditionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetInitialWaterConditionResponse.FromString,
                _registered_method=True)
        self.CreateNewWaterCondition = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/CreateNewWaterCondition',
                request_serializer=MaterialHydraulicDataService__pb2.CreateNewWaterConditionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.CreateNewWaterConditionResponse.FromString,
                _registered_method=True)
        self.DeleteWaterCondition = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/DeleteWaterCondition',
                request_serializer=MaterialHydraulicDataService__pb2.DeleteWaterConditionRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.DeleteWaterConditionResponse.FromString,
                _registered_method=True)
        self.GetWaterConditionPropertyByName = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetWaterConditionPropertyByName',
                request_serializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertyByNameRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertyByNameResponse.FromString,
                _registered_method=True)
        self.GetWaterConditionProperties = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetWaterConditionProperties',
                request_serializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertiesRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertiesResponse.FromString,
                _registered_method=True)
        self.SetWaterConditionValue = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetWaterConditionValue',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetWaterConditionValue = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetWaterConditionValue',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.CreateNewCustomHydraulicModel = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/CreateNewCustomHydraulicModel',
                request_serializer=MaterialHydraulicDataService__pb2.CreateNewCustomHydraulicModelRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.CreateNewCustomHydraulicModelResponse.FromString,
                _registered_method=True)
        self.DeleteCustomHydraulicModel = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/DeleteCustomHydraulicModel',
                request_serializer=MaterialHydraulicDataService__pb2.DeleteCustomHydraulicModelRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.DeleteCustomHydraulicModelResponse.FromString,
                _registered_method=True)
        self.GetCustomHydraulicModelPropertyByName = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetCustomHydraulicModelPropertyByName',
                request_serializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertyByNameRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertyByNameResponse.FromString,
                _registered_method=True)
        self.GetCustomHydraulicModelProperties = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetCustomHydraulicModelProperties',
                request_serializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertiesRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertiesResponse.FromString,
                _registered_method=True)
        self.SetCustomHydraulicModelType = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetCustomHydraulicModelType',
                request_serializer=MaterialHydraulicDataService__pb2.SetCustomHydraulicModelTypeRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.SetCustomHydraulicModelTypeResponse.FromString,
                _registered_method=True)
        self.GetCustomHydraulicModelType = channel.unary_unary(
                '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetCustomHydraulicModelType',
                request_serializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelTypeRequest.SerializeToString,
                response_deserializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelTypeResponse.FromString,
                _registered_method=True)


class MaterialHydraulicDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLinearDirection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinearDirection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInitialWaterCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInitialWaterCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNewWaterCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWaterCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWaterConditionPropertyByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWaterConditionProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWaterConditionValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWaterConditionValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNewCustomHydraulicModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomHydraulicModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomHydraulicModelPropertyByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomHydraulicModelProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCustomHydraulicModelType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomHydraulicModelType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaterialHydraulicDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetLinearDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLinearDirection,
                    request_deserializer=MaterialHydraulicDataService__pb2.SetLinearDirectionRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.SetLinearDirectionResponse.SerializeToString,
            ),
            'GetLinearDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinearDirection,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetLinearDirectionRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetLinearDirectionResponse.SerializeToString,
            ),
            'SetInitialWaterCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInitialWaterCondition,
                    request_deserializer=MaterialHydraulicDataService__pb2.SetInitialWaterConditionRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.SetInitialWaterConditionResponse.SerializeToString,
            ),
            'GetInitialWaterCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInitialWaterCondition,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetInitialWaterConditionRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetInitialWaterConditionResponse.SerializeToString,
            ),
            'CreateNewWaterCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewWaterCondition,
                    request_deserializer=MaterialHydraulicDataService__pb2.CreateNewWaterConditionRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.CreateNewWaterConditionResponse.SerializeToString,
            ),
            'DeleteWaterCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWaterCondition,
                    request_deserializer=MaterialHydraulicDataService__pb2.DeleteWaterConditionRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.DeleteWaterConditionResponse.SerializeToString,
            ),
            'GetWaterConditionPropertyByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaterConditionPropertyByName,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertyByNameRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertyByNameResponse.SerializeToString,
            ),
            'GetWaterConditionProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaterConditionProperties,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertiesRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetWaterConditionPropertiesResponse.SerializeToString,
            ),
            'SetWaterConditionValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWaterConditionValue,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetWaterConditionValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWaterConditionValue,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'CreateNewCustomHydraulicModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewCustomHydraulicModel,
                    request_deserializer=MaterialHydraulicDataService__pb2.CreateNewCustomHydraulicModelRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.CreateNewCustomHydraulicModelResponse.SerializeToString,
            ),
            'DeleteCustomHydraulicModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomHydraulicModel,
                    request_deserializer=MaterialHydraulicDataService__pb2.DeleteCustomHydraulicModelRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.DeleteCustomHydraulicModelResponse.SerializeToString,
            ),
            'GetCustomHydraulicModelPropertyByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomHydraulicModelPropertyByName,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertyByNameRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertyByNameResponse.SerializeToString,
            ),
            'GetCustomHydraulicModelProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomHydraulicModelProperties,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertiesRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertiesResponse.SerializeToString,
            ),
            'SetCustomHydraulicModelType': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCustomHydraulicModelType,
                    request_deserializer=MaterialHydraulicDataService__pb2.SetCustomHydraulicModelTypeRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.SetCustomHydraulicModelTypeResponse.SerializeToString,
            ),
            'GetCustomHydraulicModelType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomHydraulicModelType,
                    request_deserializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelTypeRequest.FromString,
                    response_serializer=MaterialHydraulicDataService__pb2.GetCustomHydraulicModelTypeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaterialHydraulicDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetProperty',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetProperty',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLinearDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetLinearDirection',
            MaterialHydraulicDataService__pb2.SetLinearDirectionRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.SetLinearDirectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinearDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetLinearDirection',
            MaterialHydraulicDataService__pb2.GetLinearDirectionRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetLinearDirectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInitialWaterCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetInitialWaterCondition',
            MaterialHydraulicDataService__pb2.SetInitialWaterConditionRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.SetInitialWaterConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInitialWaterCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetInitialWaterCondition',
            MaterialHydraulicDataService__pb2.GetInitialWaterConditionRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetInitialWaterConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNewWaterCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/CreateNewWaterCondition',
            MaterialHydraulicDataService__pb2.CreateNewWaterConditionRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.CreateNewWaterConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWaterCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/DeleteWaterCondition',
            MaterialHydraulicDataService__pb2.DeleteWaterConditionRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.DeleteWaterConditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWaterConditionPropertyByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetWaterConditionPropertyByName',
            MaterialHydraulicDataService__pb2.GetWaterConditionPropertyByNameRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetWaterConditionPropertyByNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWaterConditionProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetWaterConditionProperties',
            MaterialHydraulicDataService__pb2.GetWaterConditionPropertiesRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetWaterConditionPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWaterConditionValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetWaterConditionValue',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWaterConditionValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetWaterConditionValue',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNewCustomHydraulicModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/CreateNewCustomHydraulicModel',
            MaterialHydraulicDataService__pb2.CreateNewCustomHydraulicModelRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.CreateNewCustomHydraulicModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomHydraulicModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/DeleteCustomHydraulicModel',
            MaterialHydraulicDataService__pb2.DeleteCustomHydraulicModelRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.DeleteCustomHydraulicModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomHydraulicModelPropertyByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetCustomHydraulicModelPropertyByName',
            MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertyByNameRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertyByNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomHydraulicModelProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetCustomHydraulicModelProperties',
            MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertiesRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetCustomHydraulicModelPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCustomHydraulicModelType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/SetCustomHydraulicModelType',
            MaterialHydraulicDataService__pb2.SetCustomHydraulicModelTypeRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.SetCustomHydraulicModelTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustomHydraulicModelType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialHydraulicDataServiceDefinition.MaterialHydraulicDataService/GetCustomHydraulicModelType',
            MaterialHydraulicDataService__pb2.GetCustomHydraulicModelTypeRequest.SerializeToString,
            MaterialHydraulicDataService__pb2.GetCustomHydraulicModelTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
