# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MaterialJointService_pb2 as MaterialJointService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MaterialJointService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaterialJointServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetJointProperty = channel.unary_unary(
                '/MaterialJointServiceDefinition.MaterialJointService/SetJointProperty',
                request_serializer=MaterialJointService__pb2.SetJointPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointService__pb2.SetJointPropertyResponse.FromString,
                _registered_method=True)
        self.GetJointProperty = channel.unary_unary(
                '/MaterialJointServiceDefinition.MaterialJointService/GetJointProperty',
                request_serializer=MaterialJointService__pb2.GetJointPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointService__pb2.GetJointPropertyResponse.FromString,
                _registered_method=True)
        self.GetJoint = channel.unary_unary(
                '/MaterialJointServiceDefinition.MaterialJointService/GetJoint',
                request_serializer=MaterialJointService__pb2.GetJointRequest.SerializeToString,
                response_deserializer=MaterialJointService__pb2.GetJointResponse.FromString,
                _registered_method=True)


class MaterialJointServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetJointProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaterialJointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetJointProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointProperty,
                    request_deserializer=MaterialJointService__pb2.SetJointPropertyRequest.FromString,
                    response_serializer=MaterialJointService__pb2.SetJointPropertyResponse.SerializeToString,
            ),
            'GetJointProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointProperty,
                    request_deserializer=MaterialJointService__pb2.GetJointPropertyRequest.FromString,
                    response_serializer=MaterialJointService__pb2.GetJointPropertyResponse.SerializeToString,
            ),
            'GetJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJoint,
                    request_deserializer=MaterialJointService__pb2.GetJointRequest.FromString,
                    response_serializer=MaterialJointService__pb2.GetJointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MaterialJointServiceDefinition.MaterialJointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MaterialJointServiceDefinition.MaterialJointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaterialJointService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetJointProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointServiceDefinition.MaterialJointService/SetJointProperty',
            MaterialJointService__pb2.SetJointPropertyRequest.SerializeToString,
            MaterialJointService__pb2.SetJointPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointServiceDefinition.MaterialJointService/GetJointProperty',
            MaterialJointService__pb2.GetJointPropertyRequest.SerializeToString,
            MaterialJointService__pb2.GetJointPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointServiceDefinition.MaterialJointService/GetJoint',
            MaterialJointService__pb2.GetJointRequest.SerializeToString,
            MaterialJointService__pb2.GetJointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
