# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import MaterialJointSetSlipCriterionService_pb2 as MaterialJointSetSlipCriterionService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in MaterialJointSetSlipCriterionService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaterialJointSetSlipCriterionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetJointProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointPropertyResponse.FromString,
                _registered_method=True)
        self.GetJointProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointPropertyResponse.FromString,
                _registered_method=True)
        self.SetJointOptionVectorProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointOptionVectorProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionVectorPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionVectorPropertyResponse.FromString,
                _registered_method=True)
        self.GetJointOptionVectorProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointOptionVectorProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionVectorPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionVectorPropertyResponse.FromString,
                _registered_method=True)
        self.SetJointOptionTrendPlungeProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointOptionTrendPlungeProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionTrendPlungePropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionTrendPlungePropertyResponse.FromString,
                _registered_method=True)
        self.GetJointOptionTrendPlungeProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointOptionTrendPlungeProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionTrendPlungePropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionTrendPlungePropertyResponse.FromString,
                _registered_method=True)
        self.SetJointOptionDipDipDirectionProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointOptionDipDipDirectionProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionDipDipDirectionPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionDipDipDirectionPropertyResponse.FromString,
                _registered_method=True)
        self.GetJointOptionDipDipDirectionProperty = channel.unary_unary(
                '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointOptionDipDipDirectionProperty',
                request_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionDipDipDirectionPropertyRequest.SerializeToString,
                response_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionDipDipDirectionPropertyResponse.FromString,
                _registered_method=True)


class MaterialJointSetSlipCriterionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetJointProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointOptionVectorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointOptionVectorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointOptionTrendPlungeProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointOptionTrendPlungeProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointOptionDipDipDirectionProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointOptionDipDipDirectionProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaterialJointSetSlipCriterionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetJointProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointPropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointPropertyResponse.SerializeToString,
            ),
            'GetJointProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointPropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointPropertyResponse.SerializeToString,
            ),
            'SetJointOptionVectorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointOptionVectorProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionVectorPropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionVectorPropertyResponse.SerializeToString,
            ),
            'GetJointOptionVectorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointOptionVectorProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionVectorPropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionVectorPropertyResponse.SerializeToString,
            ),
            'SetJointOptionTrendPlungeProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointOptionTrendPlungeProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionTrendPlungePropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionTrendPlungePropertyResponse.SerializeToString,
            ),
            'GetJointOptionTrendPlungeProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointOptionTrendPlungeProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionTrendPlungePropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionTrendPlungePropertyResponse.SerializeToString,
            ),
            'SetJointOptionDipDipDirectionProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointOptionDipDipDirectionProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionDipDipDirectionPropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.SetJointOptionDipDipDirectionPropertyResponse.SerializeToString,
            ),
            'GetJointOptionDipDipDirectionProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointOptionDipDipDirectionProperty,
                    request_deserializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionDipDipDirectionPropertyRequest.FromString,
                    response_serializer=MaterialJointSetSlipCriterionService__pb2.GetJointOptionDipDipDirectionPropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaterialJointSetSlipCriterionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetJointProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointProperty',
            MaterialJointSetSlipCriterionService__pb2.SetJointPropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.SetJointPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointProperty',
            MaterialJointSetSlipCriterionService__pb2.GetJointPropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.GetJointPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointOptionVectorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointOptionVectorProperty',
            MaterialJointSetSlipCriterionService__pb2.SetJointOptionVectorPropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.SetJointOptionVectorPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointOptionVectorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointOptionVectorProperty',
            MaterialJointSetSlipCriterionService__pb2.GetJointOptionVectorPropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.GetJointOptionVectorPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointOptionTrendPlungeProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointOptionTrendPlungeProperty',
            MaterialJointSetSlipCriterionService__pb2.SetJointOptionTrendPlungePropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.SetJointOptionTrendPlungePropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointOptionTrendPlungeProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointOptionTrendPlungeProperty',
            MaterialJointSetSlipCriterionService__pb2.GetJointOptionTrendPlungePropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.GetJointOptionTrendPlungePropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointOptionDipDipDirectionProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/SetJointOptionDipDipDirectionProperty',
            MaterialJointSetSlipCriterionService__pb2.SetJointOptionDipDipDirectionPropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.SetJointOptionDipDipDirectionPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointOptionDipDipDirectionProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MaterialJointSetSlipCriterionServiceDefinition.MaterialJointSetSlipCriterionService/GetJointOptionDipDipDirectionProperty',
            MaterialJointSetSlipCriterionService__pb2.GetJointOptionDipDipDirectionPropertyRequest.SerializeToString,
            MaterialJointSetSlipCriterionService__pb2.GetJointOptionDipDipDirectionPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
