# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import PileForepoleResultsQueryService_pb2 as PileForepoleResultsQueryService__pb2
import ResultsQueryCommonMessage_pb2 as ResultsQueryCommonMessage__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in PileForepoleResultsQueryService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PileForepoleResultsQueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryPileForepoleNodeResults = channel.unary_stream(
                '/PileForepoleResultsQueryServiceDefinition.PileForepoleResultsQueryService/QueryPileForepoleNodeResults',
                request_serializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
                response_deserializer=ResultsQueryCommonMessage__pb2.StructuralNodeResultsResponseChunk.FromString,
                _registered_method=True)
        self.QueryPileForepoleElementResults = channel.unary_stream(
                '/PileForepoleResultsQueryServiceDefinition.PileForepoleResultsQueryService/QueryPileForepoleElementResults',
                request_serializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
                response_deserializer=PileForepoleResultsQueryService__pb2.PileForepoleElementResultsResponseChunk.FromString,
                _registered_method=True)


class PileForepoleResultsQueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryPileForepoleNodeResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPileForepoleElementResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PileForepoleResultsQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryPileForepoleNodeResults': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryPileForepoleNodeResults,
                    request_deserializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.FromString,
                    response_serializer=ResultsQueryCommonMessage__pb2.StructuralNodeResultsResponseChunk.SerializeToString,
            ),
            'QueryPileForepoleElementResults': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryPileForepoleElementResults,
                    request_deserializer=ResultsQueryCommonMessage__pb2.ResultsQueryRequest.FromString,
                    response_serializer=PileForepoleResultsQueryService__pb2.PileForepoleElementResultsResponseChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PileForepoleResultsQueryServiceDefinition.PileForepoleResultsQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PileForepoleResultsQueryServiceDefinition.PileForepoleResultsQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PileForepoleResultsQueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryPileForepoleNodeResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PileForepoleResultsQueryServiceDefinition.PileForepoleResultsQueryService/QueryPileForepoleNodeResults',
            ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
            ResultsQueryCommonMessage__pb2.StructuralNodeResultsResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPileForepoleElementResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PileForepoleResultsQueryServiceDefinition.PileForepoleResultsQueryService/QueryPileForepoleElementResults',
            ResultsQueryCommonMessage__pb2.ResultsQueryRequest.SerializeToString,
            PileForepoleResultsQueryService__pb2.PileForepoleElementResultsResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
