# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PlainStrandCableBoltService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'PlainStrandCableBoltService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!PlainStrandCableBoltService.proto\x12%PlainStrandCableBoltServiceDefinition\"B\n\x18SetBulgeLocationsRequest\x12\x0e\n\x06\x62oltId\x18\x01 \x01(\t\x12\x16\n\x0e\x62ulgeLocations\x18\x02 \x03(\x01\"\x1b\n\x19SetBulgeLocationsResponse\"*\n\x18GetBulgeLocationsRequest\x12\x0e\n\x06\x62oltId\x18\x01 \x01(\t\"3\n\x19GetBulgeLocationsResponse\x12\x16\n\x0e\x62ulgeLocations\x18\x01 \x03(\x01\x32\xcf\x02\n\x1bPlainStrandCableBoltService\x12\x96\x01\n\x11SetBulgeLocations\x12?.PlainStrandCableBoltServiceDefinition.SetBulgeLocationsRequest\x1a@.PlainStrandCableBoltServiceDefinition.SetBulgeLocationsResponse\x12\x96\x01\n\x11GetBulgeLocations\x12?.PlainStrandCableBoltServiceDefinition.GetBulgeLocationsRequest\x1a@.PlainStrandCableBoltServiceDefinition.GetBulgeLocationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlainStrandCableBoltService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETBULGELOCATIONSREQUEST']._serialized_start=76
  _globals['_SETBULGELOCATIONSREQUEST']._serialized_end=142
  _globals['_SETBULGELOCATIONSRESPONSE']._serialized_start=144
  _globals['_SETBULGELOCATIONSRESPONSE']._serialized_end=171
  _globals['_GETBULGELOCATIONSREQUEST']._serialized_start=173
  _globals['_GETBULGELOCATIONSREQUEST']._serialized_end=215
  _globals['_GETBULGELOCATIONSRESPONSE']._serialized_start=217
  _globals['_GETBULGELOCATIONSRESPONSE']._serialized_end=268
  _globals['_PLAINSTRANDCABLEBOLTSERVICE']._serialized_start=271
  _globals['_PLAINSTRANDCABLEBOLTSERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
