# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import CommonMessages_pb2 as CommonMessages__pb2
import ProjectSettingsDataService_pb2 as ProjectSettingsDataService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ProjectSettingsDataService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProjectSettingsDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProjectUnits = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetProjectUnits',
                request_serializer=ProjectSettingsDataService__pb2.SetProjectUnitRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.SetProjectUnitResponse.FromString,
                _registered_method=True)
        self.GetProjectUnits = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetProjectUnits',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetStressAnalysis = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetStressAnalysis',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetStressAnalysis = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetStressAnalysis',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetGroundwater = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetGroundwater',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetGroundwater = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetGroundwater',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetShearStrengthReduction = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetShearStrengthReduction',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetShearStrengthReduction = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetShearStrengthReduction',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetDynamic = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetDynamic',
                request_serializer=CommonMessages__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.GetDynamic = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetDynamic',
                request_serializer=CommonMessages__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=CommonMessages__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.GetDefinedStageNames = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetDefinedStageNames',
                request_serializer=ProjectSettingsDataService__pb2.GetDefinedStageNamesRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.GetDefinedStageNamesResponse.FromString,
                _registered_method=True)
        self.SetTotalNumberOfStages = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetTotalNumberOfStages',
                request_serializer=ProjectSettingsDataService__pb2.SetTotalNumberOfStagesRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.SetTotalNumberOfStagesResponse.FromString,
                _registered_method=True)
        self.AddStages = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/AddStages',
                request_serializer=ProjectSettingsDataService__pb2.AddStagesRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.AddStagesResponse.FromString,
                _registered_method=True)
        self.DeleteStages = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/DeleteStages',
                request_serializer=ProjectSettingsDataService__pb2.DeleteStagesRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.DeleteStagesResponse.FromString,
                _registered_method=True)
        self.DeleteStagesByList = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/DeleteStagesByList',
                request_serializer=ProjectSettingsDataService__pb2.DeleteStagesByListRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.DeleteStagesByListResponse.FromString,
                _registered_method=True)
        self.SetStageProperties = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetStageProperties',
                request_serializer=ProjectSettingsDataService__pb2.SetStagePropertyRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.SetStagePropertyResponse.FromString,
                _registered_method=True)
        self.GetStageProperties = channel.unary_unary(
                '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetStageProperties',
                request_serializer=ProjectSettingsDataService__pb2.GetStagePropertyRequest.SerializeToString,
                response_deserializer=ProjectSettingsDataService__pb2.GetStagePropertyResponse.FromString,
                _registered_method=True)


class ProjectSettingsDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetProjectUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStressAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStressAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGroundwater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroundwater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetShearStrengthReduction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShearStrengthReduction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDynamic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDynamic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefinedStageNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTotalNumberOfStages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStagesByList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStageProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStageProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectSettingsDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProjectUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProjectUnits,
                    request_deserializer=ProjectSettingsDataService__pb2.SetProjectUnitRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.SetProjectUnitResponse.SerializeToString,
            ),
            'GetProjectUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectUnits,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetStressAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStressAnalysis,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetStressAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStressAnalysis,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetGroundwater': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGroundwater,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetGroundwater': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroundwater,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetShearStrengthReduction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetShearStrengthReduction,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetShearStrengthReduction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShearStrengthReduction,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetDynamic': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDynamic,
                    request_deserializer=CommonMessages__pb2.SetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.SetPropertyResponse.SerializeToString,
            ),
            'GetDynamic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDynamic,
                    request_deserializer=CommonMessages__pb2.GetPropertyRequest.FromString,
                    response_serializer=CommonMessages__pb2.GetPropertyResponse.SerializeToString,
            ),
            'GetDefinedStageNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinedStageNames,
                    request_deserializer=ProjectSettingsDataService__pb2.GetDefinedStageNamesRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.GetDefinedStageNamesResponse.SerializeToString,
            ),
            'SetTotalNumberOfStages': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTotalNumberOfStages,
                    request_deserializer=ProjectSettingsDataService__pb2.SetTotalNumberOfStagesRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.SetTotalNumberOfStagesResponse.SerializeToString,
            ),
            'AddStages': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStages,
                    request_deserializer=ProjectSettingsDataService__pb2.AddStagesRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.AddStagesResponse.SerializeToString,
            ),
            'DeleteStages': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStages,
                    request_deserializer=ProjectSettingsDataService__pb2.DeleteStagesRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.DeleteStagesResponse.SerializeToString,
            ),
            'DeleteStagesByList': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStagesByList,
                    request_deserializer=ProjectSettingsDataService__pb2.DeleteStagesByListRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.DeleteStagesByListResponse.SerializeToString,
            ),
            'SetStageProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStageProperties,
                    request_deserializer=ProjectSettingsDataService__pb2.SetStagePropertyRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.SetStagePropertyResponse.SerializeToString,
            ),
            'GetStageProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStageProperties,
                    request_deserializer=ProjectSettingsDataService__pb2.GetStagePropertyRequest.FromString,
                    response_serializer=ProjectSettingsDataService__pb2.GetStagePropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProjectSettingsDataServiceDefinition.ProjectSettingsDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ProjectSettingsDataServiceDefinition.ProjectSettingsDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProjectSettingsDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetProjectUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetProjectUnits',
            ProjectSettingsDataService__pb2.SetProjectUnitRequest.SerializeToString,
            ProjectSettingsDataService__pb2.SetProjectUnitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetProjectUnits',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStressAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetStressAnalysis',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStressAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetStressAnalysis',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGroundwater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetGroundwater',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroundwater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetGroundwater',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetShearStrengthReduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetShearStrengthReduction',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShearStrengthReduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetShearStrengthReduction',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDynamic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetDynamic',
            CommonMessages__pb2.SetPropertyRequest.SerializeToString,
            CommonMessages__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDynamic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetDynamic',
            CommonMessages__pb2.GetPropertyRequest.SerializeToString,
            CommonMessages__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDefinedStageNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetDefinedStageNames',
            ProjectSettingsDataService__pb2.GetDefinedStageNamesRequest.SerializeToString,
            ProjectSettingsDataService__pb2.GetDefinedStageNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTotalNumberOfStages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetTotalNumberOfStages',
            ProjectSettingsDataService__pb2.SetTotalNumberOfStagesRequest.SerializeToString,
            ProjectSettingsDataService__pb2.SetTotalNumberOfStagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/AddStages',
            ProjectSettingsDataService__pb2.AddStagesRequest.SerializeToString,
            ProjectSettingsDataService__pb2.AddStagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/DeleteStages',
            ProjectSettingsDataService__pb2.DeleteStagesRequest.SerializeToString,
            ProjectSettingsDataService__pb2.DeleteStagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStagesByList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/DeleteStagesByList',
            ProjectSettingsDataService__pb2.DeleteStagesByListRequest.SerializeToString,
            ProjectSettingsDataService__pb2.DeleteStagesByListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStageProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/SetStageProperties',
            ProjectSettingsDataService__pb2.SetStagePropertyRequest.SerializeToString,
            ProjectSettingsDataService__pb2.SetStagePropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStageProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProjectSettingsDataServiceDefinition.ProjectSettingsDataService/GetStageProperties',
            ProjectSettingsDataService__pb2.GetStagePropertyRequest.SerializeToString,
            ProjectSettingsDataService__pb2.GetStagePropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
