# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RelativeStageFactorService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'RelativeStageFactorService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n RelativeStageFactorService.proto\x12$RelativeStageFactorServiceDefinition\"1\n\x1bGetIsRelativeStagingRequest\x12\x12\n\npropertyID\x18\x01 \x01(\t\"9\n\x1cGetIsRelativeStagingResponse\x12\x19\n\x11isRelativeStaging\x18\x01 \x01(\x08\x32\xbc\x01\n\x1aRelativeStageFactorService\x12\x9d\x01\n\x14GetIsRelativeStaging\x12\x41.RelativeStageFactorServiceDefinition.GetIsRelativeStagingRequest\x1a\x42.RelativeStageFactorServiceDefinition.GetIsRelativeStagingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RelativeStageFactorService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETISRELATIVESTAGINGREQUEST']._serialized_start=74
  _globals['_GETISRELATIVESTAGINGREQUEST']._serialized_end=123
  _globals['_GETISRELATIVESTAGINGRESPONSE']._serialized_start=125
  _globals['_GETISRELATIVESTAGINGRESPONSE']._serialized_end=182
  _globals['_RELATIVESTAGEFACTORSERVICE']._serialized_start=185
  _globals['_RELATIVESTAGEFACTORSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
