# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RFCApplicationService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bRFCApplicationService.proto\x12\x1fRFCApplicationServiceDefinition\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"#\n\x0fOpenFileRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"4\n\x10OpenFileResponse\x12\x0f\n\x07modelID\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xed\x01\n\x15RFCApplicationService\x12o\n\x08OpenFile\x12\x30.RFCApplicationServiceDefinition.OpenFileRequest\x1a\x31.RFCApplicationServiceDefinition.OpenFileResponse\x12\x63\n\x04Ping\x12,.RFCApplicationServiceDefinition.PingRequest\x1a-.RFCApplicationServiceDefinition.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RFCApplicationService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=64
  _globals['_PINGREQUEST']._serialized_end=77
  _globals['_PINGRESPONSE']._serialized_start=79
  _globals['_PINGRESPONSE']._serialized_end=93
  _globals['_OPENFILEREQUEST']._serialized_start=95
  _globals['_OPENFILEREQUEST']._serialized_end=130
  _globals['_OPENFILERESPONSE']._serialized_start=132
  _globals['_OPENFILERESPONSE']._serialized_end=184
  _globals['_RFCAPPLICATIONSERVICE']._serialized_start=187
  _globals['_RFCAPPLICATIONSERVICE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
