# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SelectionService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'SelectionService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CommonGeometryMessages_pb2 as CommonGeometryMessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SelectionService.proto\x12\x1aSelectionServiceDefinition\x1a\x1c\x43ommonGeometryMessages.proto\"\x8b\x01\n$_getExternalVolumesByGeometryRequest\x12\x12\n\n_projectId\x18\x01 \x01(\t\x12\x32\n\x08geometry\x18\x02 \x01(\x0b\x32 .CommonGeometryMessages.Geometry\x12\x1b\n\x13includeIntersecting\x18\x03 \x01(\x08\"7\n%_getExternalVolumesByGeometryResponse\x12\x0e\n\x06result\x18\x01 \x03(\t\"R\n!getAttachedExternalVolumesRequest\x12\x12\n\n_projectId\x18\x01 \x01(\t\x12\x19\n\x11_externalVolumeID\x18\x02 \x01(\t\"4\n\"getAttachedExternalVolumesResponse\x12\x0e\n\x06result\x18\x01 \x03(\t\"_\n-getAttachedExternalVolumesByVolumeNameRequest\x12\x12\n\n_projectId\x18\x01 \x01(\t\x12\x1a\n\x12\x65xternalVolumeName\x18\x02 \x01(\t\"@\n.getAttachedExternalVolumesByVolumeNameResponse\x12\x0e\n\x06result\x18\x01 \x03(\t2\xea\x06\n\x10SelectionService\x12\xa1\x01\n\x1a_getExternalVolumesByPoint\x12@.SelectionServiceDefinition._getExternalVolumesByGeometryRequest\x1a\x41.SelectionServiceDefinition._getExternalVolumesByGeometryResponse\x12\xa4\x01\n\x1d_getExternalVolumesByPolyline\x12@.SelectionServiceDefinition._getExternalVolumesByGeometryRequest\x1a\x41.SelectionServiceDefinition._getExternalVolumesByGeometryResponse\x12\xaa\x01\n#_getExternalVolumesByBoundingVolume\x12@.SelectionServiceDefinition._getExternalVolumesByGeometryRequest\x1a\x41.SelectionServiceDefinition._getExternalVolumesByGeometryResponse\x12\x9b\x01\n\x1agetAttachedExternalVolumes\x12=.SelectionServiceDefinition.getAttachedExternalVolumesRequest\x1a>.SelectionServiceDefinition.getAttachedExternalVolumesResponse\x12\xbf\x01\n&getAttachedExternalVolumesByVolumeName\x12I.SelectionServiceDefinition.getAttachedExternalVolumesByVolumeNameRequest\x1aJ.SelectionServiceDefinition.getAttachedExternalVolumesByVolumeNameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SelectionService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['__GETEXTERNALVOLUMESBYGEOMETRYREQUEST']._serialized_start=85
  _globals['__GETEXTERNALVOLUMESBYGEOMETRYREQUEST']._serialized_end=224
  _globals['__GETEXTERNALVOLUMESBYGEOMETRYRESPONSE']._serialized_start=226
  _globals['__GETEXTERNALVOLUMESBYGEOMETRYRESPONSE']._serialized_end=281
  _globals['_GETATTACHEDEXTERNALVOLUMESREQUEST']._serialized_start=283
  _globals['_GETATTACHEDEXTERNALVOLUMESREQUEST']._serialized_end=365
  _globals['_GETATTACHEDEXTERNALVOLUMESRESPONSE']._serialized_start=367
  _globals['_GETATTACHEDEXTERNALVOLUMESRESPONSE']._serialized_end=419
  _globals['_GETATTACHEDEXTERNALVOLUMESBYVOLUMENAMEREQUEST']._serialized_start=421
  _globals['_GETATTACHEDEXTERNALVOLUMESBYVOLUMENAMEREQUEST']._serialized_end=516
  _globals['_GETATTACHEDEXTERNALVOLUMESBYVOLUMENAMERESPONSE']._serialized_start=518
  _globals['_GETATTACHEDEXTERNALVOLUMESBYVOLUMENAMERESPONSE']._serialized_end=582
  _globals['_SELECTIONSERVICE']._serialized_start=585
  _globals['_SELECTIONSERVICE']._serialized_end=1459
# @@protoc_insertion_point(module_scope)
