# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import SolidsResultsQueryService_pb2 as SolidsResultsQueryService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in SolidsResultsQueryService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolidResultsQueryServiceStub(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadResultsByStageSRFValueAndDataTypes = channel.unary_unary(
                '/SolidsResultsQueryServiceDefinition.SolidResultsQueryService/ReadResultsByStageSRFValueAndDataTypes',
                request_serializer=SolidsResultsQueryService__pb2.SolidResultsByDataTypesQueryRequest.SerializeToString,
                response_deserializer=SolidsResultsQueryService__pb2.SolidResultsByDataTypesQueryResponse.FromString,
                _registered_method=True)
        self.QuerySolidNodalResults = channel.unary_stream(
                '/SolidsResultsQueryServiceDefinition.SolidResultsQueryService/QuerySolidNodalResults',
                request_serializer=SolidsResultsQueryService__pb2.SolidNodalResultsQueryRequest.SerializeToString,
                response_deserializer=SolidsResultsQueryService__pb2.SolidNodalResultsResponseChunk.FromString,
                _registered_method=True)
        self.QuerySolidElementResults = channel.unary_stream(
                '/SolidsResultsQueryServiceDefinition.SolidResultsQueryService/QuerySolidElementResults',
                request_serializer=SolidsResultsQueryService__pb2.SolidResultsQueryRequest.SerializeToString,
                response_deserializer=SolidsResultsQueryService__pb2.SolidElementResultsResponseChunk.FromString,
                _registered_method=True)


class SolidResultsQueryServiceServicer(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def ReadResultsByStageSRFValueAndDataTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySolidNodalResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySolidElementResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolidResultsQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadResultsByStageSRFValueAndDataTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResultsByStageSRFValueAndDataTypes,
                    request_deserializer=SolidsResultsQueryService__pb2.SolidResultsByDataTypesQueryRequest.FromString,
                    response_serializer=SolidsResultsQueryService__pb2.SolidResultsByDataTypesQueryResponse.SerializeToString,
            ),
            'QuerySolidNodalResults': grpc.unary_stream_rpc_method_handler(
                    servicer.QuerySolidNodalResults,
                    request_deserializer=SolidsResultsQueryService__pb2.SolidNodalResultsQueryRequest.FromString,
                    response_serializer=SolidsResultsQueryService__pb2.SolidNodalResultsResponseChunk.SerializeToString,
            ),
            'QuerySolidElementResults': grpc.unary_stream_rpc_method_handler(
                    servicer.QuerySolidElementResults,
                    request_deserializer=SolidsResultsQueryService__pb2.SolidResultsQueryRequest.FromString,
                    response_serializer=SolidsResultsQueryService__pb2.SolidElementResultsResponseChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SolidsResultsQueryServiceDefinition.SolidResultsQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SolidsResultsQueryServiceDefinition.SolidResultsQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SolidResultsQueryService(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    @staticmethod
    def ReadResultsByStageSRFValueAndDataTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SolidsResultsQueryServiceDefinition.SolidResultsQueryService/ReadResultsByStageSRFValueAndDataTypes',
            SolidsResultsQueryService__pb2.SolidResultsByDataTypesQueryRequest.SerializeToString,
            SolidsResultsQueryService__pb2.SolidResultsByDataTypesQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySolidNodalResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SolidsResultsQueryServiceDefinition.SolidResultsQueryService/QuerySolidNodalResults',
            SolidsResultsQueryService__pb2.SolidNodalResultsQueryRequest.SerializeToString,
            SolidsResultsQueryService__pb2.SolidNodalResultsResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySolidElementResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SolidsResultsQueryServiceDefinition.SolidResultsQueryService/QuerySolidElementResults',
            SolidsResultsQueryService__pb2.SolidResultsQueryRequest.SerializeToString,
            SolidsResultsQueryService__pb2.SolidElementResultsResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
