# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import WaterPressureGridDataService_pb2 as WaterPressureGridDataService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in WaterPressureGridDataService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WaterPressureGridDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetProperty = channel.unary_unary(
                '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/SetProperty',
                request_serializer=WaterPressureGridDataService__pb2.SetProjectPropertyRequest.SerializeToString,
                response_deserializer=WaterPressureGridDataService__pb2.SetProjectPropertyResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/GetProperty',
                request_serializer=WaterPressureGridDataService__pb2.GetProjectPropertyRequest.SerializeToString,
                response_deserializer=WaterPressureGridDataService__pb2.GetProjectPropertyResponse.FromString,
                _registered_method=True)
        self.SetColorProperty = channel.unary_unary(
                '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/SetColorProperty',
                request_serializer=WaterPressureGridDataService__pb2.SetProjectColorRequest.SerializeToString,
                response_deserializer=WaterPressureGridDataService__pb2.SetProjectColorResponse.FromString,
                _registered_method=True)
        self.GetColorProperty = channel.unary_unary(
                '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/GetColorProperty',
                request_serializer=WaterPressureGridDataService__pb2.GetProjectColorRequest.SerializeToString,
                response_deserializer=WaterPressureGridDataService__pb2.GetProjectColorResponse.FromString,
                _registered_method=True)
        self.SetPWPPointSet = channel.unary_unary(
                '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/SetPWPPointSet',
                request_serializer=WaterPressureGridDataService__pb2.SetPWPPointSetRequest.SerializeToString,
                response_deserializer=WaterPressureGridDataService__pb2.SetPWPPointSetResponse.FromString,
                _registered_method=True)
        self.GetPWPPointSet = channel.unary_unary(
                '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/GetPWPPointSet',
                request_serializer=WaterPressureGridDataService__pb2.GetPWPPointSetRequest.SerializeToString,
                response_deserializer=WaterPressureGridDataService__pb2.GetPWPPointSetResponse.FromString,
                _registered_method=True)


class WaterPressureGridDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetColorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColorProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPWPPointSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPWPPointSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterPressureGridDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=WaterPressureGridDataService__pb2.SetProjectPropertyRequest.FromString,
                    response_serializer=WaterPressureGridDataService__pb2.SetProjectPropertyResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=WaterPressureGridDataService__pb2.GetProjectPropertyRequest.FromString,
                    response_serializer=WaterPressureGridDataService__pb2.GetProjectPropertyResponse.SerializeToString,
            ),
            'SetColorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetColorProperty,
                    request_deserializer=WaterPressureGridDataService__pb2.SetProjectColorRequest.FromString,
                    response_serializer=WaterPressureGridDataService__pb2.SetProjectColorResponse.SerializeToString,
            ),
            'GetColorProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColorProperty,
                    request_deserializer=WaterPressureGridDataService__pb2.GetProjectColorRequest.FromString,
                    response_serializer=WaterPressureGridDataService__pb2.GetProjectColorResponse.SerializeToString,
            ),
            'SetPWPPointSet': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPWPPointSet,
                    request_deserializer=WaterPressureGridDataService__pb2.SetPWPPointSetRequest.FromString,
                    response_serializer=WaterPressureGridDataService__pb2.SetPWPPointSetResponse.SerializeToString,
            ),
            'GetPWPPointSet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPWPPointSet,
                    request_deserializer=WaterPressureGridDataService__pb2.GetPWPPointSetRequest.FromString,
                    response_serializer=WaterPressureGridDataService__pb2.GetPWPPointSetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WaterPressureGridDataServiceDefinition.WaterPressureGridDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('WaterPressureGridDataServiceDefinition.WaterPressureGridDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaterPressureGridDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/SetProperty',
            WaterPressureGridDataService__pb2.SetProjectPropertyRequest.SerializeToString,
            WaterPressureGridDataService__pb2.SetProjectPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/GetProperty',
            WaterPressureGridDataService__pb2.GetProjectPropertyRequest.SerializeToString,
            WaterPressureGridDataService__pb2.GetProjectPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetColorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/SetColorProperty',
            WaterPressureGridDataService__pb2.SetProjectColorRequest.SerializeToString,
            WaterPressureGridDataService__pb2.SetProjectColorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetColorProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/GetColorProperty',
            WaterPressureGridDataService__pb2.GetProjectColorRequest.SerializeToString,
            WaterPressureGridDataService__pb2.GetProjectColorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPWPPointSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/SetPWPPointSet',
            WaterPressureGridDataService__pb2.SetPWPPointSetRequest.SerializeToString,
            WaterPressureGridDataService__pb2.SetPWPPointSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPWPPointSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WaterPressureGridDataServiceDefinition.WaterPressureGridDataService/GetPWPPointSet',
            WaterPressureGridDataService__pb2.GetPWPPointSetRequest.SerializeToString,
            WaterPressureGridDataService__pb2.GetPWPPointSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
