# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor, LoadingMaterialStiffnessFormulaPropertyAccessor, UnloadingMaterialStiffnessFormulaPropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.StiffnessStageFactorService_pb2_grpc as StiffnessStageFactorService_pb2_grpc
class Formula2Base(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
        self._unloadingPropertyAccessor = PropertyAccessor(client, id)
    def getInitialE(self) -> float:
        return self._propertyAccessor.getDoubleProperty("InitialE")
    def setInitialE(self, value: float):
        self._propertyAccessor.setDoubleProperty("InitialE", value)
    def getPref(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Pref")
    def setPref(self, value: float):
        self._propertyAccessor.setDoubleProperty("Pref", value)
    def getAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("A")
    def setAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("A", value)
    def getBParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("B")
    def setBParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("B", value)
    def getMParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("M")
    def setMParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("M", value)
    def getUnloadingInitialE(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("InitialE")
    def setUnloadingInitialE(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("InitialE", value)
    def getUnloadingPref(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("Pref")
    def setUnloadingPref(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("Pref", value)
    def getUnloadingAParameter(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("A")
    def setUnloadingAParameter(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("A", value)
    def getUnloadingBParameter(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("B")
    def setUnloadingBParameter(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("B", value)
    def getUnloadingMParameter(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("M")
    def setUnloadingMParameter(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("M", value)
    def getProperties(self):
        return {
            "InitialE": self.getInitialE(),
            "Pref": self.getPref(),
            "AParameter": self.getAParameter(),
            "BParameter": self.getBParameter(),
            "MParameter": self.getMParameter(),
            "UnloadingInitialE": self.getUnloadingInitialE(),
            "UnloadingPref": self.getUnloadingPref(),
            "UnloadingAParameter": self.getUnloadingAParameter(),
            "UnloadingBParameter": self.getUnloadingBParameter(),
            "UnloadingMParameter": self.getUnloadingMParameter(),
        }
    def setProperties(self, InitialE: float = None, Pref: float = None, AParameter: float = None, BParameter: float = None, MParameter: float = None, UnloadingInitialE: float = None, UnloadingPref: float = None, UnloadingAParameter: float = None, UnloadingBParameter: float = None, UnloadingMParameter: float = None):
        if InitialE is not None:
            self.setInitialE(InitialE)
        if Pref is not None:
            self.setPref(Pref)
        if AParameter is not None:
            self.setAParameter(AParameter)
        if BParameter is not None:
            self.setBParameter(BParameter)
        if MParameter is not None:
            self.setMParameter(MParameter)
        if UnloadingInitialE is not None:
            self.setUnloadingInitialE(UnloadingInitialE)
        if UnloadingPref is not None:
            self.setUnloadingPref(UnloadingPref)
        if UnloadingAParameter is not None:
            self.setUnloadingAParameter(UnloadingAParameter)
        if UnloadingBParameter is not None:
            self.setUnloadingBParameter(UnloadingBParameter)
        if UnloadingMParameter is not None:
            self.setUnloadingMParameter(UnloadingMParameter)
class Formula2StageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, StiffnessStageFactorService_pb2_grpc.StiffnessStageFactorServiceStub(client.channel))
    def getAParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula2_a")
    def getAlphaFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula2_Alpha")
    def getBParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula2_b")
    def getInitialEFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula2_InitialE")
    def getMParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula2_m")
    def getPrefFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula2_Pref")
class Formula2DefinedStageFactorBase(Formula2StageFactorBase):
    def setAParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula2_a", value)
    def setAlphaFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula2_Alpha", value)
    def setBParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula2_b", value)
    def setInitialEFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula2_InitialE", value)
    def setMParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula2_m", value)
    def setPrefFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula2_Pref", value)

################ Code below this line will not be overridden ################
from ._PropertyAccessor import LoadingMaterialStiffnessFormulaPropertyAccessor, UnloadingMaterialStiffnessFormulaPropertyAccessor
from rs3.properties.material.constitutiveModel.stiffness.GeneralizedHoekBrownEstimation import GeneralizedHoekBrownEstimation
import rs3.generatedFiles.MaterialStiffnessFormulaService_pb2 as MaterialStiffnessFormulaService_pb2
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface

class Formula2StageFactor(Formula2StageFactorBase):
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class Formula2DefinedStageFactor(Formula2DefinedStageFactorBase):
    pass

class Formula2(Formula2Base):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = LoadingMaterialStiffnessFormulaPropertyAccessor(client, id, MaterialStiffnessFormulaService_pb2.IsotropicFormulaType.FORMULA_2)
        self._unloadingPropertyAccessor = UnloadingMaterialStiffnessFormulaPropertyAccessor(client, id, MaterialStiffnessFormulaService_pb2.IsotropicFormulaType.FORMULA_2)
        self.GeneralizedHoekBrownEstimation = GeneralizedHoekBrownEstimation(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[Formula2DefinedStageFactor, Formula2StageFactor](id, client, Formula2DefinedStageFactor, Formula2StageFactor)
        