# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor, LoadingMaterialStiffnessFormulaPropertyAccessor, UnloadingMaterialStiffnessFormulaPropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.StiffnessStageFactorService_pb2_grpc as StiffnessStageFactorService_pb2_grpc
class Formula1Base(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
        self._unloadingPropertyAccessor = PropertyAccessor(client, id)
    def getInitialE(self) -> float:
        return self._propertyAccessor.getDoubleProperty("InitialE")
    def setInitialE(self, value: float):
        self._propertyAccessor.setDoubleProperty("InitialE", value)
    def getPref(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Pref")
    def setPref(self, value: float):
        self._propertyAccessor.setDoubleProperty("Pref", value)
    def getAlpha(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Alpha")
    def setAlpha(self, value: float):
        self._propertyAccessor.setDoubleProperty("Alpha", value)
    def getUnloadingInitialE(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("InitialE")
    def setUnloadingInitialE(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("InitialE", value)
    def getUnloadingPref(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("Pref")
    def setUnloadingPref(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("Pref", value)
    def getUnloadingAlpha(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("Alpha")
    def setUnloadingAlpha(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("Alpha", value)
    def getProperties(self):
        return {
            "InitialE": self.getInitialE(),
            "Pref": self.getPref(),
            "Alpha": self.getAlpha(),
            "UnloadingInitialE": self.getUnloadingInitialE(),
            "UnloadingPref": self.getUnloadingPref(),
            "UnloadingAlpha": self.getUnloadingAlpha(),
        }
    def setProperties(self, InitialE: float = None, Pref: float = None, Alpha: float = None, UnloadingInitialE: float = None, UnloadingPref: float = None, UnloadingAlpha: float = None):
        if InitialE is not None:
            self.setInitialE(InitialE)
        if Pref is not None:
            self.setPref(Pref)
        if Alpha is not None:
            self.setAlpha(Alpha)
        if UnloadingInitialE is not None:
            self.setUnloadingInitialE(UnloadingInitialE)
        if UnloadingPref is not None:
            self.setUnloadingPref(UnloadingPref)
        if UnloadingAlpha is not None:
            self.setUnloadingAlpha(UnloadingAlpha)
class Formula1StageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, StiffnessStageFactorService_pb2_grpc.StiffnessStageFactorServiceStub(client.channel))
    def getAlphaFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula1_Alpha")
    def getInitialEFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula1_InitialE")
    def getPrefFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Formula1_Pref")
class Formula1DefinedStageFactorBase(Formula1StageFactorBase):
    def setAlphaFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula1_Alpha", value)
    def setInitialEFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula1_InitialE", value)
    def setPrefFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Formula1_Pref", value)

################ Code below this line will not be overridden ################
from ._PropertyAccessor import LoadingMaterialStiffnessFormulaPropertyAccessor, UnloadingMaterialStiffnessFormulaPropertyAccessor
from rs3.properties.material.constitutiveModel.stiffness.GeneralizedHoekBrownEstimation import GeneralizedHoekBrownEstimation
import rs3.generatedFiles.MaterialStiffnessFormulaService_pb2 as MaterialStiffnessFormulaService_pb2
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface

class Formula1StageFactor(Formula1StageFactorBase):
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class Formula1DefinedStageFactor(Formula1DefinedStageFactorBase):
    pass

class Formula1(Formula1Base):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = LoadingMaterialStiffnessFormulaPropertyAccessor(client, id, MaterialStiffnessFormulaService_pb2.IsotropicFormulaType.FORMULA_1)
        self._unloadingPropertyAccessor = UnloadingMaterialStiffnessFormulaPropertyAccessor(client, id, MaterialStiffnessFormulaService_pb2.IsotropicFormulaType.FORMULA_1)
        self.GeneralizedHoekBrownEstimation = GeneralizedHoekBrownEstimation(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[Formula1DefinedStageFactor, Formula1StageFactor](id, client, Formula1DefinedStageFactor, Formula1StageFactor)
        