# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.JointStageFactorService_pb2_grpc as JointStageFactorService_pb2_grpc
class BartonBandisBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getJCS(self) -> float:
        return self._propertyAccessor.getDoubleProperty("JCS")
    def setJCS(self, value: float):
        self._propertyAccessor.setDoubleProperty("JCS", value)
    def getJRC(self) -> float:
        return self._propertyAccessor.getDoubleProperty("JRC")
    def setJRC(self, value: float):
        self._propertyAccessor.setDoubleProperty("JRC", value)
    def getNormalStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("NormalStiffness")
    def setNormalStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("NormalStiffness", value)
    def getShearStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ShearStiffness")
    def setShearStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("ShearStiffness", value)
    def getResidualFrictionAngle(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FrictionAngleResidual")
    def setResidualFrictionAngle(self, value: float):
        self._propertyAccessor.setDoubleProperty("FrictionAngleResidual", value)
    def getDefineResidualStrength(self) -> bool:
        return self._propertyAccessor.getBoolValue("HasResidualStrength")
    def setDefineResidualStrength(self, value: bool):
        self._propertyAccessor.setBoolValue("HasResidualStrength", value)
    def getProperties(self):
        return {
            "JCS": self.getJCS(),
            "JRC": self.getJRC(),
            "NormalStiffness": self.getNormalStiffness(),
            "ShearStiffness": self.getShearStiffness(),
            "ResidualFrictionAngle": self.getResidualFrictionAngle(),
            "DefineResidualStrength": self.getDefineResidualStrength(),
        }
    def setProperties(self, JCS: float = None, JRC: float = None, NormalStiffness: float = None, ShearStiffness: float = None, ResidualFrictionAngle: float = None, DefineResidualStrength: bool = None):
        if JCS is not None:
            self.setJCS(JCS)
        if JRC is not None:
            self.setJRC(JRC)
        if NormalStiffness is not None:
            self.setNormalStiffness(NormalStiffness)
        if ShearStiffness is not None:
            self.setShearStiffness(ShearStiffness)
        if ResidualFrictionAngle is not None:
            self.setResidualFrictionAngle(ResidualFrictionAngle)
        if DefineResidualStrength is not None:
            self.setDefineResidualStrength(DefineResidualStrength)
class BartonBandisStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, JointStageFactorService_pb2_grpc.JointStageFactorServiceStub(client.channel))
    def getResidualFrictionAngleFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("BartonBandis_FrictionAngleResidual")
    def getJCSFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("BartonBandis_JCSFactor")
    def getJRCFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("BartonBandis_JRCFactor")
    def getNormalStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("BartonBandis_NormalStiffness")
    def getShearStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("BartonBandis_ShearStiffness")
class BartonBandisDefinedStageFactorBase(BartonBandisStageFactorBase):
    def setResidualFrictionAngleFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("BartonBandis_FrictionAngleResidual", value)
    def setJCSFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("BartonBandis_JCSFactor", value)
    def setJRCFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("BartonBandis_JRCFactor", value)
    def setNormalStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("BartonBandis_NormalStiffness", value)
    def setShearStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("BartonBandis_ShearStiffness", value)

################ Code below this line will not be overridden ################
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
import rs3.generatedFiles.JointService_pb2_grpc as JointService_pb2_grpc
import rs3.generatedFiles.JointService_pb2 as JointService_pb2

class BartonBandisStageFactor(BartonBandisStageFactorBase):
    """
	Examples:
		See :ref:`joint_example`.
	"""
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class BartonBandisDefinedStageFactor(BartonBandisStageFactor, BartonBandisDefinedStageFactorBase):
    """
	Examples:
		See :ref:`joint_example`.
	"""
    pass

class BartonBandis(BartonBandisBase):
    """
	Examples:
		See :ref:`joint_example`.
	"""
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._jointService = JointService_pb2_grpc.JointServiceStub(self._client.channel)
        self.StageFactorInterface = AbsoluteStageFactorInterface[BartonBandisDefinedStageFactor, BartonBandisStageFactor](id, client, BartonBandisDefinedStageFactor, BartonBandisStageFactor)
    def getAllowSlipStartFromStage(self) -> int:
        request = JointService_pb2.GetSlipStageRequest(jointId=self._objectId)
        respond : JointService_pb2.GetSlipStageResponse = self._client.callFunction(self._jointService.GetSlipStage, request)
        return respond.slipStageNumber
    def setAllowSlipStartFromStage(self, value: int):
        request = JointService_pb2.SetSlipStageRequest(jointId=self._objectId, slipStageNumber=value)
        self._client.callFunction(self._jointService.SetSlipStage, request)