# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.JointStageFactorService_pb2_grpc as JointStageFactorService_pb2_grpc
class MohrCoulombBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getDilationAngle(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DilationAngle")
    def setDilationAngle(self, value: float):
        self._propertyAccessor.setDoubleProperty("DilationAngle", value)
    def getNormalStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("NormalStiffness")
    def setNormalStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("NormalStiffness", value)
    def getShearStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ShearStiffness")
    def setShearStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("ShearStiffness", value)
    def getCohesion(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PeakCohesion")
    def setCohesion(self, value: float):
        self._propertyAccessor.setDoubleProperty("PeakCohesion", value)
    def getFrictionAngle(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PeakFrictionAngle")
    def setFrictionAngle(self, value: float):
        self._propertyAccessor.setDoubleProperty("PeakFrictionAngle", value)
    def getTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("TensileStrength")
    def setTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("TensileStrength", value)
    def getDefineResidualStrength(self) -> bool:
        return self._propertyAccessor.getBoolValue("HasResidualStrength")
    def setDefineResidualStrength(self, value: bool):
        self._propertyAccessor.setBoolValue("HasResidualStrength", value)
    def getDirectional(self) -> bool:
        return self._propertyAccessor.getBoolValue("IsDirectional")
    def setDirectional(self, value: bool):
        self._propertyAccessor.setBoolValue("IsDirectional", value)
    def getResidualCohesion(self) -> float:
        return self._propertyAccessor.getDoubleProperty("CohesionResidual")
    def setResidualCohesion(self, value: float):
        self._propertyAccessor.setDoubleProperty("CohesionResidual", value)
    def getResidualFrictionAngle(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FrictionAngleResidual")
    def setResidualFrictionAngle(self, value: float):
        self._propertyAccessor.setDoubleProperty("FrictionAngleResidual", value)
    def getResidualTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("TensileStrengthResidual")
    def setResidualTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("TensileStrengthResidual", value)
    def getProperties(self):
        return {
            "DilationAngle": self.getDilationAngle(),
            "NormalStiffness": self.getNormalStiffness(),
            "ShearStiffness": self.getShearStiffness(),
            "Cohesion": self.getCohesion(),
            "FrictionAngle": self.getFrictionAngle(),
            "TensileStrength": self.getTensileStrength(),
            "DefineResidualStrength": self.getDefineResidualStrength(),
            "Directional": self.getDirectional(),
            "ResidualCohesion": self.getResidualCohesion(),
            "ResidualFrictionAngle": self.getResidualFrictionAngle(),
            "ResidualTensileStrength": self.getResidualTensileStrength(),
        }
    def setProperties(self, DilationAngle: float = None, NormalStiffness: float = None, ShearStiffness: float = None, Cohesion: float = None, FrictionAngle: float = None, TensileStrength: float = None, DefineResidualStrength: bool = None, Directional: bool = None, ResidualCohesion: float = None, ResidualFrictionAngle: float = None, ResidualTensileStrength: float = None):
        if DilationAngle is not None:
            self.setDilationAngle(DilationAngle)
        if NormalStiffness is not None:
            self.setNormalStiffness(NormalStiffness)
        if ShearStiffness is not None:
            self.setShearStiffness(ShearStiffness)
        if Cohesion is not None:
            self.setCohesion(Cohesion)
        if FrictionAngle is not None:
            self.setFrictionAngle(FrictionAngle)
        if TensileStrength is not None:
            self.setTensileStrength(TensileStrength)
        if DefineResidualStrength is not None:
            self.setDefineResidualStrength(DefineResidualStrength)
        if Directional is not None:
            self.setDirectional(Directional)
        if ResidualCohesion is not None:
            self.setResidualCohesion(ResidualCohesion)
        if ResidualFrictionAngle is not None:
            self.setResidualFrictionAngle(ResidualFrictionAngle)
        if ResidualTensileStrength is not None:
            self.setResidualTensileStrength(ResidualTensileStrength)
class MohrCoulombStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, JointStageFactorService_pb2_grpc.JointStageFactorServiceStub(client.channel))
    def getDilationAngleFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_DilationAngleFactor")
    def getNormalStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_NormalStiffness")
    def getCohesionFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_PeakCohesionFactor")
    def getFrictionAngleFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_PeakFrictionAngleFactor")
    def getResidualCohesionFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_ResidualCohesionFactor")
    def getResidualFrictionAngleFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_ResidualFrictionAngleFactor")
    def getResidualTensileStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_ResidualTensileStrengthFactor")
    def getShearStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_ShearStiffness")
    def getTensileStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("MohrCoulomb_TensileStrengthFactor")
class MohrCoulombDefinedStageFactorBase(MohrCoulombStageFactorBase):
    def setDilationAngleFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_DilationAngleFactor", value)
    def setNormalStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_NormalStiffness", value)
    def setCohesionFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_PeakCohesionFactor", value)
    def setFrictionAngleFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_PeakFrictionAngleFactor", value)
    def setResidualCohesionFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_ResidualCohesionFactor", value)
    def setResidualFrictionAngleFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_ResidualFrictionAngleFactor", value)
    def setResidualTensileStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_ResidualTensileStrengthFactor", value)
    def setShearStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_ShearStiffness", value)
    def setTensileStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("MohrCoulomb_TensileStrengthFactor", value)

################ Code below this line will not be overridden ################
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
import rs3.generatedFiles.JointService_pb2_grpc as JointService_pb2_grpc
import rs3.generatedFiles.JointService_pb2 as JointService_pb2

class MohrCoulombStageFactor(MohrCoulombStageFactorBase):
    """
	Examples:
		See :ref:`joint_example`.
	"""
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class MohrCoulombDefinedStageFactor(MohrCoulombStageFactor, MohrCoulombDefinedStageFactorBase):
    """
	Examples:
		See :ref:`joint_example`.
	"""
    pass

class MohrCoulomb(MohrCoulombBase):
    """
	Examples:
		See :ref:`joint_example`.
	"""
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._jointService = JointService_pb2_grpc.JointServiceStub(self._client.channel)
        self.StageFactorInterface = AbsoluteStageFactorInterface[MohrCoulombDefinedStageFactor, MohrCoulombStageFactor](id, client, MohrCoulombDefinedStageFactor, MohrCoulombStageFactor)    
    def getAllowSlipStartFromStage(self) -> int:
        request = JointService_pb2.GetSlipStageRequest(jointId=self._objectId)
        respond : JointService_pb2.GetSlipStageResponse = self._client.callFunction(self._jointService.GetSlipStage, request)
        return respond.slipStageNumber
    def setAllowSlipStartFromStage(self, value: int):
        request = JointService_pb2.SetSlipStageRequest(jointId=self._objectId, slipStageNumber=value)
        self._client.callFunction(self._jointService.SetSlipStage, request)