# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.BeamStageFactorService_pb2_grpc as BeamStageFactorService_pb2_grpc
class BeamCommonBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getYoungsModulus(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Modulus")
    def setYoungsModulus(self, value: float):
        self._propertyAccessor.setDoubleProperty("Modulus", value)
    def getPoissonsRatio(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PoissonRatio")
    def setPoissonsRatio(self, value: float):
        self._propertyAccessor.setDoubleProperty("PoissonRatio", value)
    def getShearStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ShearStrength")
    def setShearStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("ShearStrength", value)
    def getArea(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Area")
    def setArea(self, value: float):
        self._propertyAccessor.setDoubleProperty("Area", value)
    def getUnitWeight(self) -> float:
        return self._propertyAccessor.getDoubleProperty("UnitWeight")
    def setUnitWeight(self, value: float):
        self._propertyAccessor.setDoubleProperty("UnitWeight", value)
    def getPreTensioning(self) -> bool:
        return self._propertyAccessor.getBoolValue("PreTensioning")
    def setPreTensioning(self, value: bool):
        self._propertyAccessor.setBoolValue("PreTensioning", value)
    def getPreTensioningForce(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PreTensioningForce")
    def setPreTensioningForce(self, value: float):
        self._propertyAccessor.setDoubleProperty("PreTensioningForce", value)
    def getIncludeWeightInStressAnalysis(self) -> bool:
        return self._propertyAccessor.getBoolValue("WeightInAnalysis")
    def setIncludeWeightInStressAnalysis(self, value: bool):
        self._propertyAccessor.setBoolValue("WeightInAnalysis", value)
    def getCompressiveStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PeakCompressiveStrength")
    def setCompressiveStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("PeakCompressiveStrength", value)
    def getTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PeakTensileStrength")
    def setTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("PeakTensileStrength", value)
    def getResidualCompressiveStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ResidualCompressiveStrength")
    def setResidualCompressiveStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("ResidualCompressiveStrength", value)
    def getResidualTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ResidualTensileStrength")
    def setResidualTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("ResidualTensileStrength", value)
    def getProperties(self):
        return {
            "YoungsModulus": self.getYoungsModulus(),
            "PoissonsRatio": self.getPoissonsRatio(),
            "ShearStrength": self.getShearStrength(),
            "Area": self.getArea(),
            "UnitWeight": self.getUnitWeight(),
            "PreTensioning": self.getPreTensioning(),
            "PreTensioningForce": self.getPreTensioningForce(),
            "IncludeWeightInStressAnalysis": self.getIncludeWeightInStressAnalysis(),
            "CompressiveStrength": self.getCompressiveStrength(),
            "TensileStrength": self.getTensileStrength(),
            "ResidualCompressiveStrength": self.getResidualCompressiveStrength(),
            "ResidualTensileStrength": self.getResidualTensileStrength(),
        }
    def setProperties(self, YoungsModulus: float = None, PoissonsRatio: float = None, ShearStrength: float = None, Area: float = None, UnitWeight: float = None, PreTensioning: bool = None, PreTensioningForce: float = None, IncludeWeightInStressAnalysis: bool = None, CompressiveStrength: float = None, TensileStrength: float = None, ResidualCompressiveStrength: float = None, ResidualTensileStrength: float = None):
        if YoungsModulus is not None:
            self.setYoungsModulus(YoungsModulus)
        if PoissonsRatio is not None:
            self.setPoissonsRatio(PoissonsRatio)
        if ShearStrength is not None:
            self.setShearStrength(ShearStrength)
        if Area is not None:
            self.setArea(Area)
        if UnitWeight is not None:
            self.setUnitWeight(UnitWeight)
        if PreTensioning is not None:
            self.setPreTensioning(PreTensioning)
        if PreTensioningForce is not None:
            self.setPreTensioningForce(PreTensioningForce)
        if IncludeWeightInStressAnalysis is not None:
            self.setIncludeWeightInStressAnalysis(IncludeWeightInStressAnalysis)
        if CompressiveStrength is not None:
            self.setCompressiveStrength(CompressiveStrength)
        if TensileStrength is not None:
            self.setTensileStrength(TensileStrength)
        if ResidualCompressiveStrength is not None:
            self.setResidualCompressiveStrength(ResidualCompressiveStrength)
        if ResidualTensileStrength is not None:
            self.setResidualTensileStrength(ResidualTensileStrength)
class BeamCommonStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, BeamStageFactorService_pb2_grpc.BeamStageFactorServiceStub(client.channel))
    def getAreaFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_Area")
    def getCompressiveStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_CompressiveStrengthPeak")
    def getResidualCompressiveStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_CompressiveStrengthResidual")
    def getPoissonsRatioFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_PoissonsRatio")
    def getPretensionForceFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_PretensionForce")
    def getTensileStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_TensileStrengthPeak")
    def getResidualTensileStrengthFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_TensileStrengthResidual")
    def getUnitWeightFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_UnitWeight")
    def getYoungsModulusFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_YoungsModulus")
class BeamCommonDefinedStageFactorBase(BeamCommonStageFactorBase):
    def setAreaFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_Area", value)
    def setCompressiveStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_CompressiveStrengthPeak", value)
    def setResidualCompressiveStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_CompressiveStrengthResidual", value)
    def setPoissonsRatioFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_PoissonsRatio", value)
    def setPretensionForceFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_PretensionForce", value)
    def setTensileStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_TensileStrengthPeak", value)
    def setResidualTensileStrengthFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_TensileStrengthResidual", value)
    def setUnitWeightFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_UnitWeight", value)
    def setYoungsModulusFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_YoungsModulus", value)

################ Code below this line will not be overridden ################     
from rs3.properties.PropertyEnums import *
class BeamCommonStageFactor(BeamCommonStageFactorBase):
    """
    Examples:
        See :ref:`beam_example`.
    """
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class BeamCommonDefinedStageFactor(BeamCommonDefinedStageFactorBase):
    """
    Examples:
        See :ref:`beam_example`.
    """
    pass

class BeamCommon(BeamCommonBase):
    """
    Common base class for all beam-type structural elements.

    ``BeamCommon`` defines the shared properties that are applicable to 
    both Standard beam and Truss. 
    
    Examples:
        See :ref:`beam_example`.
    """
    
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)

    def setMaterialType(self, value : MaterialType):
        self._propertyAccessor.setBoolValue("IsPlasticMaterial", value.value)
    def getMaterialType(self) -> MaterialType:
        return MaterialType(self._propertyAccessor.getBoolValue("IsPlasticMaterial"))