# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.HydraulicStageFactorService_pb2_grpc as HydraulicStageFactorService_pb2_grpc
class BrooksBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getPoreSizeIndex(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PoreSizeIndex")
    def setPoreSizeIndex(self, value: float):
        self._propertyAccessor.setDoubleProperty("PoreSizeIndex", value)
    def getBubblingPressure(self) -> float:
        return self._propertyAccessor.getDoubleProperty("BubblingPressure")
    def setBubblingPressure(self, value: float):
        self._propertyAccessor.setDoubleProperty("BubblingPressure", value)
    def getProperties(self):
        return {
            "PoreSizeIndex": self.getPoreSizeIndex(),
            "BubblingPressure": self.getBubblingPressure(),
        }
    def setProperties(self, PoreSizeIndex: float = None, BubblingPressure: float = None):
        if PoreSizeIndex is not None:
            self.setPoreSizeIndex(PoreSizeIndex)
        if BubblingPressure is not None:
            self.setBubblingPressure(BubblingPressure)
class BrooksStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, HydraulicStageFactorService_pb2_grpc.HydraulicStageFactorServiceStub(client.channel))
    def getPoreSizeIndexFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_PoreSizeIndex")
    def getBubblingPressureFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_BubblingPressure")
class BrooksDefinedStageFactorBase(BrooksStageFactorBase):
    def setPoreSizeIndexFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_PoreSizeIndex", value)
    def setBubblingPressureFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_BubblingPressure", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
from rs3.properties.material.hydraulic.FEAGroundwater.HydraulicParametersCommon import HydraulicParametersCommon, HydraulicParametersCommonStageFactor, HydraulicParametersCommonDefinedStageFactor

class BrooksStageFactor(BrooksStageFactorBase, HydraulicParametersCommonStageFactor):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class BrooksDefinedStageFactor(BrooksDefinedStageFactorBase, BrooksStageFactor, HydraulicParametersCommonDefinedStageFactor):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    pass

class Brooks(BrooksBase, HydraulicParametersCommon):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[BrooksDefinedStageFactor, BrooksStageFactor](id, client, BrooksDefinedStageFactor, BrooksStageFactor)
        