# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import BasePropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.HydraulicStageFactorService_pb2_grpc as HydraulicStageFactorService_pb2_grpc
class CustomBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._basePropertyAccessor = BasePropertyAccessor(client, id)
    def getMv(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("MV")
    def setMv(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("MV", value)
    def getPermeabilityK2K1Ratio(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("K2K1Ratio")
    def setPermeabilityK2K1Ratio(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("K2K1Ratio", value)
    def getPermeabilityK3K1Ratio(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("K3K1Ratio")
    def setPermeabilityK3K1Ratio(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("K3K1Ratio", value)
    def getProperties(self):
        return {
            "Mv": self.getMv(),
            "PermeabilityK2K1Ratio": self.getPermeabilityK2K1Ratio(),
            "PermeabilityK3K1Ratio": self.getPermeabilityK3K1Ratio(),
        }
    def setProperties(self, Mv: float = None, PermeabilityK2K1Ratio: float = None, PermeabilityK3K1Ratio: float = None):
        if Mv is not None:
            self.setMv(Mv)
        if PermeabilityK2K1Ratio is not None:
            self.setPermeabilityK2K1Ratio(PermeabilityK2K1Ratio)
        if PermeabilityK3K1Ratio is not None:
            self.setPermeabilityK3K1Ratio(PermeabilityK3K1Ratio)
class CustomStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client, stub):
        super().__init__(id, stageFactorID, client, stub)
    def getPermeabilityK2K1RatioFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_K2K1Ratio")
    def getPermeabilityK3K1RatioFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_K3K1Ratio")
class CustomDefinedStageFactorBase(CustomStageFactorBase):
    def setPermeabilityK2K1RatioFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_K2K1Ratio", value)
    def setPermeabilityK3K1RatioFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_K3K1Ratio", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
from rs3.properties.material.hydraulic.FEAGroundwater.HydraulicMethodVectors import HydraulicMethodVectors
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
class CustomStageFactor(CustomStageFactorBase):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client, HydraulicStageFactorService_pb2_grpc.HydraulicStageFactorServiceStub(client.channel))
class CustomDefinedStageFactor(CustomStageFactor, CustomDefinedStageFactorBase):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    pass
class Custom(CustomBase, HydraulicMethodVectors):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, client: Client, objectId: str):
        super().__init__(client, objectId)
        self.StageFactorInterface = AbsoluteStageFactorInterface[CustomDefinedStageFactor, CustomStageFactor](objectId, client, CustomDefinedStageFactor, CustomStageFactor)
        
    def setHydraulicMethodType(self, hydraulicMethodType : HydraulicMethodType):
        self._basePropertyAccessor.setEnumValue("MethodType", hydraulicMethodType.value)
    def getHydraulicMethodType(self) -> HydraulicMethodType:
        return self._basePropertyAccessor.getEnumValue("MethodType", HydraulicMethodType)