# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.PropertyEnums import *
from rs3.CommonEnums import *
from rs3.properties.material.hydraulic.FEAGroundwater.Brooks import Brooks
from rs3.properties.material.hydraulic.FEAGroundwater.Fredlund import Fredlund
from rs3.properties.material.hydraulic.FEAGroundwater.Simple import Simple
from rs3.properties.material.hydraulic.FEAGroundwater.Gardner import Gardner
from rs3.properties.material.hydraulic.FEAGroundwater.VanGenuchten import VanGenuchten
from rs3.properties.material.hydraulic.FEAGroundwater.Custom import Custom
from rs3.properties.material.hydraulic._PropertyAccessor import PropertyAccessor as NewPropertyAccessor
import rs3.generatedFiles.MaterialHydraulicDataService_pb2_grpc as MaterialHydraulicDataService_pb2_grpc
import rs3.generatedFiles.MaterialHydraulicDataService_pb2 as MaterialHydraulicDataService_pb2
class FEAGroundwater(_ProxyObject):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = NewPropertyAccessor(client, id)
        self._stub = MaterialHydraulicDataService_pb2_grpc.MaterialHydraulicDataServiceStub(client.channel)
        self.Brooks = Brooks(client, id)
        self.Fredlund = Fredlund(client, id)
        self.Simple = Simple(client, id)
        self.Gardner = Gardner(client, id)
        self.VanGenuchten = VanGenuchten(client, id)
        self.Custom = Custom(client, id)
                
    def setHydraulicModelType(self, hydraulicModelType : HydraulicModelType, customHydraulicModelName : str = ""):
        """
        Set the hydraulic model type for the current material.

        If setting a standard hydraulic model, specify the `hydraulicModelType` as one of the predefined `HydraulicModelType` enum values.  

        If setting a custom hydraulic model, set `hydraulicModelType` to `HydraulicModelType.CUSTOM` and provide a non-empty `customHydraulicModelName`.
        The method will send the custom name to the service instead of using the standard enum property.

        Args:
            hydraulicModelType (HydraulicModelType):
                The type of hydraulic model to set.
                - Standard models: use the corresponding `HydraulicModelType` enum.
                - Custom model: use `HydraulicModelType.CUSTOM`.
            customHydraulicModelName (str, optional):
                The name of the custom hydraulic model, required when `hydraulicModelType` is `CUSTOM`. Ignored for standard models.

        Raises:
            ValueError: If `hydraulicModelType` is `CUSTOM` and no `customHydraulicModelName` is provided.
        """
        if hydraulicModelType == HydraulicModelType.CUSTOM and customHydraulicModelName is None:
            raise ValueError("Custom hydraulic moodel name is required.")
        elif hydraulicModelType == HydraulicModelType.CUSTOM and customHydraulicModelName is not None:
            request = MaterialHydraulicDataService_pb2.SetCustomHydraulicModelTypeRequest(objectId=self._objectId, value=customHydraulicModelName)
            self._client.callFunction(self._stub.SetCustomHydraulicModelType, request)
        else:
            self._propertyAccessor.setIntProperty("ModelType", hydraulicModelType.value)
    def getHydraulicModelType(self) -> HydraulicModelType | str:
        """
        Retrieve the current hydraulic model type for the material.

        - If the current model is a **standard hydraulic model**, this method returns the corresponding `HydraulicModelType` enum value.
        - If the current model is a **custom hydraulic model**, this method returns the custom hydraulic model name as a string.

        Returns:
            HydraulicModelType | str:
                - `HydraulicModelType` enum for standard models.
                - `str` for the custom hydraulic model name.

        Raises:
            ValueError: If the response does not contain a valid value.
        """
        request = MaterialHydraulicDataService_pb2.GetCustomHydraulicModelTypeRequest(objectId=self._objectId)
        response : MaterialHydraulicDataService_pb2.GetCustomHydraulicModelTypeResponse = self._client.callFunction(self._stub.GetCustomHydraulicModelType, request)
        
        field = response.value.WhichOneof("value")

        if field == "intValue":
            return HydraulicModelType(response.value.intValue)
        elif field == "stringValue":
            return response.value.stringValue
        else:
            raise ValueError("No valid value found in response.")