# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.HydraulicStageFactorService_pb2_grpc as HydraulicStageFactorService_pb2_grpc
class FredlundBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getA(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FredXingA")
    def setA(self, value: float):
        self._propertyAccessor.setDoubleProperty("FredXingA", value)
    def getB(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FredXingB")
    def setB(self, value: float):
        self._propertyAccessor.setDoubleProperty("FredXingB", value)
    def getC(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FredXingC")
    def setC(self, value: float):
        self._propertyAccessor.setDoubleProperty("FredXingC", value)
    def getProperties(self):
        return {
            "A": self.getA(),
            "B": self.getB(),
            "C": self.getC(),
        }
    def setProperties(self, A: float = None, B: float = None, C: float = None):
        if A is not None:
            self.setA(A)
        if B is not None:
            self.setB(B)
        if C is not None:
            self.setC(C)
class FredlundStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, HydraulicStageFactorService_pb2_grpc.HydraulicStageFactorServiceStub(client.channel))
    def getAFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_FredXingA")
    def getBFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_FredXingB")
    def getCFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_FredXingC")
class FredlundDefinedStageFactorBase(FredlundStageFactorBase):
    def setAFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_FredXingA", value)
    def setBFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_FredXingB", value)
    def setCFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_FredXingC", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
from rs3.properties.material.hydraulic.FEAGroundwater.HydraulicParametersCommon import HydraulicParametersCommon, HydraulicParametersCommonStageFactor, HydraulicParametersCommonDefinedStageFactor

class FredlundStageFactor(FredlundStageFactorBase, HydraulicParametersCommonStageFactor):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class FredlundDefinedStageFactor(FredlundDefinedStageFactorBase, FredlundStageFactor, HydraulicParametersCommonDefinedStageFactor):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    pass

class Fredlund(FredlundBase, HydraulicParametersCommon):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[FredlundDefinedStageFactor, FredlundStageFactor](id, client, FredlundDefinedStageFactor, FredlundStageFactor)
        