# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.HydraulicStageFactorService_pb2_grpc as HydraulicStageFactorService_pb2_grpc
class GardnerBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getA(self) -> float:
        return self._propertyAccessor.getDoubleProperty("GardnerA")
    def setA(self, value: float):
        self._propertyAccessor.setDoubleProperty("GardnerA", value)
    def getN(self) -> float:
        return self._propertyAccessor.getDoubleProperty("GardnerN")
    def setN(self, value: float):
        self._propertyAccessor.setDoubleProperty("GardnerN", value)
    def getProperties(self):
        return {
            "A": self.getA(),
            "N": self.getN(),
        }
    def setProperties(self, A: float = None, N: float = None):
        if A is not None:
            self.setA(A)
        if N is not None:
            self.setN(N)
class GardnerStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, HydraulicStageFactorService_pb2_grpc.HydraulicStageFactorServiceStub(client.channel))
    def getAFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_GardnerA")
    def getNFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_GardnerN")
class GardnerDefinedStageFactorBase(GardnerStageFactorBase):
    def setAFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_GardnerA", value)
    def setNFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_GardnerN", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
from rs3.properties.material.hydraulic.FEAGroundwater.HydraulicParametersCommon import HydraulicParametersCommon, HydraulicParametersCommonStageFactor, HydraulicParametersCommonDefinedStageFactor

class GardnerStageFactor(GardnerStageFactorBase, HydraulicParametersCommonStageFactor):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class GardnerDefinedStageFactor(GardnerDefinedStageFactorBase, GardnerStageFactor, HydraulicParametersCommonDefinedStageFactor):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    pass

class Gardner(GardnerBase, HydraulicParametersCommon):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[GardnerDefinedStageFactor, GardnerStageFactor](id, client, GardnerDefinedStageFactor, GardnerStageFactor)
        
        