# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import BasePropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.HydraulicStageFactorService_pb2_grpc as HydraulicStageFactorService_pb2_grpc
class HydraulicParametersCommonBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._basePropertyAccessor = BasePropertyAccessor(client, id)
    def getPermeabilityK(self) -> float:
        """
        Get isotropic permeability.
        """
        return self._basePropertyAccessor.getDoubleProperty("PermeabilityForLinearIsotropic")
    def setPermeabilityK(self, value: float):
        """
        Set isotropic permeability.
        """
        self._basePropertyAccessor.setDoubleProperty("PermeabilityForLinearIsotropic", value)
    def getPermeabilityK1(self) -> float:
        """
        Get anisotropic permeability.
        """
        return self._basePropertyAccessor.getDoubleProperty("Permeability")
    def setPermeabilityK1(self, value: float):
        """
        Set anisotropic permeability.
        """
        self._basePropertyAccessor.setDoubleProperty("Permeability", value)
    def getMv(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("MV")
    def setMv(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("MV", value)
    def getWCSat(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("WCSat")
    def setWCSat(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("WCSat", value)
    def getWCRes(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("WCRes")
    def setWCRes(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("WCRes", value)
    def getPermeabilityK2K1Ratio(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("K2K1Ratio")
    def setPermeabilityK2K1Ratio(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("K2K1Ratio", value)
    def getPermeabilityK3K1Ratio(self) -> float:
        return self._basePropertyAccessor.getDoubleProperty("K3K1Ratio")
    def setPermeabilityK3K1Ratio(self, value: float):
        self._basePropertyAccessor.setDoubleProperty("K3K1Ratio", value)
    def getProperties(self):
        return {
            "PermeabilityK": self.getPermeabilityK(),
            "PermeabilityK1": self.getPermeabilityK1(),
            "Mv": self.getMv(),
            "WCSat": self.getWCSat(),
            "WCRes": self.getWCRes(),
            "PermeabilityK2K1Ratio": self.getPermeabilityK2K1Ratio(),
            "PermeabilityK3K1Ratio": self.getPermeabilityK3K1Ratio(),
        }
    def setProperties(self, PermeabilityK: float = None, PermeabilityK1: float = None, Mv: float = None, WCSat: float = None, WCRes: float = None, PermeabilityK2K1Ratio: float = None, PermeabilityK3K1Ratio: float = None):
        if PermeabilityK is not None:
            self.setPermeabilityK(PermeabilityK)
        if PermeabilityK1 is not None:
            self.setPermeabilityK1(PermeabilityK1)
        if Mv is not None:
            self.setMv(Mv)
        if WCSat is not None:
            self.setWCSat(WCSat)
        if WCRes is not None:
            self.setWCRes(WCRes)
        if PermeabilityK2K1Ratio is not None:
            self.setPermeabilityK2K1Ratio(PermeabilityK2K1Ratio)
        if PermeabilityK3K1Ratio is not None:
            self.setPermeabilityK3K1Ratio(PermeabilityK3K1Ratio)
class HydraulicParametersCommonStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client, stub):
        super().__init__(id, stageFactorID, client, stub)
    def getPermeabilityKFactor(self) -> float:
        """
        Get isotropic permeability factor.
        """
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_Permeability")
    def getPermeabilityK1AngleFactor(self) -> float:
        """
        Get anisotropic permeability angle factor.
        """
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_K1Angle")
    def getMvFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_MV")
    def getWCSatFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_WCSat")
    def getWCResFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_WCRes")
    def getPermeabilityK2K1RatioFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_K2K1Ratio")
    def getPermeabilityK3K1RatioFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GW_K3K1Ratio")
class HydraulicParametersCommonDefinedStageFactorBase(HydraulicParametersCommonStageFactorBase):
    def setPermeabilityKFactor(self, value: float):
        """
        Set isotropic permeability factor.
        """
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_Permeability", value)
    def setPermeabilityK1AngleFactor(self, value: float):
        """
        Set anisotropic permeability angle factor.
        """
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_K1Angle", value)
    def setMvFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_MV", value)
    def setWCSatFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_WCSat", value)
    def setWCResFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_WCRes", value)
    def setPermeabilityK2K1RatioFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_K2K1Ratio", value)
    def setPermeabilityK3K1RatioFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GW_K3K1Ratio", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface
from rs3.properties.material.hydraulic.FEAGroundwater.HydraulicMethodVectors import HydraulicMethodVectors
import rs3.generatedFiles.MaterialHydraulicDataService_pb2_grpc as MaterialHydraulicDataService_pb2_grpc

class HydraulicParametersCommonStageFactor(HydraulicParametersCommonStageFactorBase):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, id : str, stageFactorID : str, client : Client, stub):
        super().__init__(id, stageFactorID, client, stub)
        
class HydraulicParametersCommonDefinedStageFactor(HydraulicParametersCommonStageFactor, HydraulicParametersCommonDefinedStageFactorBase):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    pass

class HydraulicParametersCommon(HydraulicParametersCommonBase, HydraulicMethodVectors):
    """
	Examples:
		See :ref:`material_hydraulic_example`.
    """
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stub = MaterialHydraulicDataService_pb2_grpc.MaterialHydraulicDataServiceStub(client.channel)
        self.StageFactorInterface = AbsoluteStageFactorInterface[HydraulicParametersCommonDefinedStageFactor, HydraulicParametersCommonStageFactor](id, client, HydraulicParametersCommonDefinedStageFactor, HydraulicParametersCommonStageFactor)
    
    def setHydraulicMethodType(self, hydraulicMethodType : HydraulicMethodType):
        self._basePropertyAccessor.setEnumValue("MethodType", hydraulicMethodType.value)
    def getHydraulicMethodType(self) -> HydraulicMethodType:
        return self._basePropertyAccessor.getEnumValue("MethodType", HydraulicMethodType)    
    