# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.PileStageFactorService_pb2_grpc as PileStageFactorService_pb2_grpc
class PileCommonBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getShearStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ShearStiffness")
    def setShearStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("ShearStiffness", value)
    def getNormalStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("NormalStiffness")
    def setNormalStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("NormalStiffness", value)
    def getUsingPileProperties(self) -> bool:
        return self._propertyAccessor.getBoolValue("IsPile")
    def setUsingPileProperties(self, value: bool):
        self._propertyAccessor.setBoolValue("IsPile", value)
    def getBaseNormalStiffness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("BaseNormalStiffness")
    def setBaseNormalStiffness(self, value: float):
        self._propertyAccessor.setDoubleProperty("BaseNormalStiffness", value)
    def getBaseForceResistance(self) -> float:
        return self._propertyAccessor.getDoubleProperty("BaseForceResistance")
    def setBaseForceResistance(self, value: float):
        self._propertyAccessor.setDoubleProperty("BaseForceResistance", value)
    def getProperties(self):
        return {
            "ShearStiffness": self.getShearStiffness(),
            "NormalStiffness": self.getNormalStiffness(),
            "UsingPileProperties": self.getUsingPileProperties(),
            "BaseNormalStiffness": self.getBaseNormalStiffness(),
            "BaseForceResistance": self.getBaseForceResistance(),
        }
    def setProperties(self, ShearStiffness: float = None, NormalStiffness: float = None, UsingPileProperties: bool = None, BaseNormalStiffness: float = None, BaseForceResistance: float = None):
        if ShearStiffness is not None:
            self.setShearStiffness(ShearStiffness)
        if NormalStiffness is not None:
            self.setNormalStiffness(NormalStiffness)
        if UsingPileProperties is not None:
            self.setUsingPileProperties(UsingPileProperties)
        if BaseNormalStiffness is not None:
            self.setBaseNormalStiffness(BaseNormalStiffness)
        if BaseForceResistance is not None:
            self.setBaseForceResistance(BaseForceResistance)
class PileCommonStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, PileStageFactorService_pb2_grpc.PileStageFactorServiceStub(client.channel))
    def getEndConditionFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_Force")
    def getShearStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_ShearStiffness")
    def getNormalStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_NormalStiffness")
    def getBaseStiffnessFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_BaseStiffness")
    def getBaseResistanceFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("Common_BaseResistance")
class PileCommonDefinedStageFactorBase(PileCommonStageFactorBase):
    def setEndConditionFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_Force", value)
    def setShearStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_ShearStiffness", value)
    def setNormalStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_NormalStiffness", value)
    def setBaseStiffnessFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_BaseStiffness", value)
    def setBaseResistanceFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("Common_BaseResistance", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
class PileCommonStageFactor(PileCommonStageFactorBase):
    """
	Examples:
		See :ref:`pile_example`.
	"""
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class PileCommonDefinedStageFactor(PileCommonStageFactor, PileCommonDefinedStageFactorBase):
    """
	Examples:
		See :ref:`pile_example`.
	"""
    pass

class PileCommon(PileCommonBase):
    """
	Examples:
		See :ref:`pile_example`.
	"""    
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)