# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
class AnisotropicLinearBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getUseTensileStrength(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseTensile")
    def setUseTensileStrength(self, value: bool):
        self._propertyAccessor.setBoolValue("UseTensile", value)
    def getCohesion1(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Cohesion1")
    def setCohesion1(self, value: float):
        self._propertyAccessor.setDoubleProperty("Cohesion1", value)
    def getCohesion2(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Cohesion2")
    def setCohesion2(self, value: float):
        self._propertyAccessor.setDoubleProperty("Cohesion2", value)
    def getFrictionAngle1(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FrictionAngle1")
    def setFrictionAngle1(self, value: float):
        self._propertyAccessor.setDoubleProperty("FrictionAngle1", value)
    def getFrictionAngle2(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FrictionAngle2")
    def setFrictionAngle2(self, value: float):
        self._propertyAccessor.setDoubleProperty("FrictionAngle2", value)
    def getResidualCohesion1(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Cohesion1Residual")
    def setResidualCohesion1(self, value: float):
        self._propertyAccessor.setDoubleProperty("Cohesion1Residual", value)
    def getResidualCohesion2(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Cohesion2Residual")
    def setResidualCohesion2(self, value: float):
        self._propertyAccessor.setDoubleProperty("Cohesion2Residual", value)
    def getResidualFrictionAngle1(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FrictionAngle1Residual")
    def setResidualFrictionAngle1(self, value: float):
        self._propertyAccessor.setDoubleProperty("FrictionAngle1Residual", value)
    def getResidualFrictionAngle2(self) -> float:
        return self._propertyAccessor.getDoubleProperty("FrictionAngle2Residual")
    def setResidualFrictionAngle2(self, value: float):
        self._propertyAccessor.setDoubleProperty("FrictionAngle2Residual", value)
    def getDilationAngle1(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DilationAngle1")
    def setDilationAngle1(self, value: float):
        self._propertyAccessor.setDoubleProperty("DilationAngle1", value)
    def getDilationAngle2(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DilationAngle2")
    def setDilationAngle2(self, value: float):
        self._propertyAccessor.setDoubleProperty("DilationAngle2", value)
    def getResidualTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("TensileStrengthResidual")
    def setResidualTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("TensileStrengthResidual", value)
    def getA1Parameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("A1Parameter")
    def setA1Parameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("A1Parameter", value)
    def getB1Parameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("B1Parameter")
    def setB1Parameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("B1Parameter", value)
    def getTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PeakTensileStrength")
    def setTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("PeakTensileStrength", value)
    def getProperties(self):
        return {
            "UseTensileStrength": self.getUseTensileStrength(),
            "Cohesion1": self.getCohesion1(),
            "Cohesion2": self.getCohesion2(),
            "FrictionAngle1": self.getFrictionAngle1(),
            "FrictionAngle2": self.getFrictionAngle2(),
            "ResidualCohesion1": self.getResidualCohesion1(),
            "ResidualCohesion2": self.getResidualCohesion2(),
            "ResidualFrictionAngle1": self.getResidualFrictionAngle1(),
            "ResidualFrictionAngle2": self.getResidualFrictionAngle2(),
            "DilationAngle1": self.getDilationAngle1(),
            "DilationAngle2": self.getDilationAngle2(),
            "ResidualTensileStrength": self.getResidualTensileStrength(),
            "A1Parameter": self.getA1Parameter(),
            "B1Parameter": self.getB1Parameter(),
            "TensileStrength": self.getTensileStrength(),
        }
    def setProperties(self, UseTensileStrength: bool = None, Cohesion1: float = None, Cohesion2: float = None, FrictionAngle1: float = None, FrictionAngle2: float = None, ResidualCohesion1: float = None, ResidualCohesion2: float = None, ResidualFrictionAngle1: float = None, ResidualFrictionAngle2: float = None, DilationAngle1: float = None, DilationAngle2: float = None, ResidualTensileStrength: float = None, A1Parameter: float = None, B1Parameter: float = None, TensileStrength: float = None):
        if UseTensileStrength is not None:
            self.setUseTensileStrength(UseTensileStrength)
        if Cohesion1 is not None:
            self.setCohesion1(Cohesion1)
        if Cohesion2 is not None:
            self.setCohesion2(Cohesion2)
        if FrictionAngle1 is not None:
            self.setFrictionAngle1(FrictionAngle1)
        if FrictionAngle2 is not None:
            self.setFrictionAngle2(FrictionAngle2)
        if ResidualCohesion1 is not None:
            self.setResidualCohesion1(ResidualCohesion1)
        if ResidualCohesion2 is not None:
            self.setResidualCohesion2(ResidualCohesion2)
        if ResidualFrictionAngle1 is not None:
            self.setResidualFrictionAngle1(ResidualFrictionAngle1)
        if ResidualFrictionAngle2 is not None:
            self.setResidualFrictionAngle2(ResidualFrictionAngle2)
        if DilationAngle1 is not None:
            self.setDilationAngle1(DilationAngle1)
        if DilationAngle2 is not None:
            self.setDilationAngle2(DilationAngle2)
        if ResidualTensileStrength is not None:
            self.setResidualTensileStrength(ResidualTensileStrength)
        if A1Parameter is not None:
            self.setA1Parameter(A1Parameter)
        if B1Parameter is not None:
            self.setB1Parameter(B1Parameter)
        if TensileStrength is not None:
            self.setTensileStrength(TensileStrength)

################ Code below this line will not be overridden ################
from rs3.properties.material.constitutiveModel.stiffness.LinearIsotropic import LinearIsotropic
from rs3.properties.material.constitutiveModel.stiffness.TransverselyIsotropic import TransverselyIsotropic
from rs3.properties.material.constitutiveModel.stiffness.Orthotropic import Orthotropic
from rs3.properties.material.constitutiveModel.stiffness.DuncanChangHyperbolic import DuncanChangHyperbolic
from rs3.properties.material.constitutiveModel.stiffness.NonlinearIsotropic import NonlinearIsotropic
from rs3.properties.material.constitutiveModel.AnisotropicLinearPlanarBase import AnisotropicLinearPlanarBase
from rs3.properties.material.constitutiveModel.BaseConstitutiveModel import BaseConstitutiveModel
from rs3.properties.material.constitutiveModel.UnsaturatedZoneCalculations import UnsaturatedZoneCalculations
from rs3.properties._PropertyAccessor import PropertyAccessor as BasePropertyAccessor
import rs3.generatedFiles.MaterialDataService_pb2_grpc as MaterialDataService_pb2_grpc
from rs3.properties.PropertyEnums import *
class AnisotropicLinear(AnisotropicLinearBase, AnisotropicLinearPlanarBase, BaseConstitutiveModel):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stiffnessPropertyAccessor = BasePropertyAccessor(client, id, MaterialDataService_pb2_grpc.MaterialDataServiceStub(self._client.channel))
        self.LinearIsotropicStiffness = LinearIsotropic(client, id)
        self.TransverselyIsotropicStiffness = TransverselyIsotropic(client, id)
        self.OrthotropicStiffness = Orthotropic(client, id)
        self.DuncanChangHyperbolicStiffness = DuncanChangHyperbolic(client, id)
        self.NonlinearIsotropicStiffness = NonlinearIsotropic(client, id)
        self.UnsaturatedZoneCalculations = UnsaturatedZoneCalculations(client, id)
        
    def getAnisotropyDefinition(self) -> AnisotropyDefinitionType:
        return self._propertyAccessor.getEnumValue("AnisotropyDefinition", AnisotropyDefinitionType)
    def setAnisotropyDefinition(self, AnisotropyDefinition: AnisotropyDefinitionType):
        return self._propertyAccessor.setEnumValue("AnisotropyDefinition", AnisotropyDefinition.value)
    
    
    