# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
class BartonBandisBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getPhiR(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PhiR")
    def setPhiR(self, value: float):
        self._propertyAccessor.setDoubleProperty("PhiR", value)
    def getJRC(self) -> float:
        return self._propertyAccessor.getDoubleProperty("JRC")
    def setJRC(self, value: float):
        self._propertyAccessor.setDoubleProperty("JRC", value)
    def getJCS(self) -> float:
        return self._propertyAccessor.getDoubleProperty("JCS")
    def setJCS(self, value: float):
        self._propertyAccessor.setDoubleProperty("JCS", value)
    def getDilationAngle(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DilationAngle")
    def setDilationAngle(self, value: float):
        self._propertyAccessor.setDoubleProperty("DilationAngle", value)
    def getResidualStrength(self) -> bool:
        return self._propertyAccessor.getBoolValue("ResidualStrength")
    def setResidualStrength(self, value: bool):
        self._propertyAccessor.setBoolValue("ResidualStrength", value)
    def getApplySSRShearStrengthReduction(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseSSR")
    def setApplySSRShearStrengthReduction(self, value: bool):
        self._propertyAccessor.setBoolValue("UseSSR", value)
    def getProperties(self):
        return {
            "PhiR": self.getPhiR(),
            "JRC": self.getJRC(),
            "JCS": self.getJCS(),
            "DilationAngle": self.getDilationAngle(),
            "ResidualStrength": self.getResidualStrength(),
            "ApplySSRShearStrengthReduction": self.getApplySSRShearStrengthReduction(),
        }
    def setProperties(self, PhiR: float = None, JRC: float = None, JCS: float = None, DilationAngle: float = None, ResidualStrength: bool = None, ApplySSRShearStrengthReduction: bool = None):
        if PhiR is not None:
            self.setPhiR(PhiR)
        if JRC is not None:
            self.setJRC(JRC)
        if JCS is not None:
            self.setJCS(JCS)
        if DilationAngle is not None:
            self.setDilationAngle(DilationAngle)
        if ResidualStrength is not None:
            self.setResidualStrength(ResidualStrength)
        if ApplySSRShearStrengthReduction is not None:
            self.setApplySSRShearStrengthReduction(ApplySSRShearStrengthReduction)

################ Code below this line will not be overridden ################
from rs3.properties.material.constitutiveModel.stiffness.LinearIsotropic import LinearIsotropic
from rs3.properties.material.constitutiveModel.stiffness.TransverselyIsotropic import TransverselyIsotropic
from rs3.properties.material.constitutiveModel.stiffness.Orthotropic import Orthotropic
from rs3.properties.material.constitutiveModel.stiffness.DuncanChangHyperbolic import DuncanChangHyperbolic
from rs3.properties.material.constitutiveModel.stiffness.NonlinearIsotropic import NonlinearIsotropic
from rs3.properties.material.constitutiveModel.BaseConstitutiveModel import BaseConstitutiveModel
from rs3.properties.material.constitutiveModel.UnsaturatedZoneCalculations import UnsaturatedZoneCalculations
from rs3.properties._PropertyAccessor import PropertyAccessor as BasePropertyAccessor
import rs3.generatedFiles.MaterialDataService_pb2_grpc as MaterialDataService_pb2_grpc
from rs3.properties.PropertyEnums import *
class BartonBandis(BartonBandisBase, BaseConstitutiveModel):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stiffnessPropertyAccessor = BasePropertyAccessor(client, id, MaterialDataService_pb2_grpc.MaterialDataServiceStub(self._client.channel))
        self.LinearIsotropicStiffness = LinearIsotropic(client, id)
        self.TransverselyIsotropicStiffness = TransverselyIsotropic(client, id)
        self.OrthotropicStiffness = Orthotropic(client, id)
        self.DuncanChangHyperbolicStiffness = DuncanChangHyperbolic(client, id)
        self.NonlinearIsotropicStiffness = NonlinearIsotropic(client, id)
        self.UnsaturatedZoneCalculations = UnsaturatedZoneCalculations(client, id)