# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.StrengthStageFactorService_pb2_grpc as StrengthStageFactorService_pb2_grpc
class JointedGeneralizedHoekBrownBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getIntactUCS(self) -> float:
        return self._propertyAccessor.getDoubleProperty("IntactCompressiveStrengthValue")
    def setIntactUCS(self, value: float):
        self._propertyAccessor.setDoubleProperty("IntactCompressiveStrengthValue", value)
    def getMbParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("MbParameter")
    def setMbParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("MbParameter", value)
    def getSParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("SParameter")
    def setSParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("SParameter", value)
    def getAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("AParameter")
    def setAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("AParameter", value)
    def getResidualMbParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("MbParameterResidual")
    def setResidualMbParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("MbParameterResidual", value)
    def getResidualSParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("SParameterResidual")
    def setResidualSParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("SParameterResidual", value)
    def getResidualAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("AParameterResidual")
    def setResidualAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("AParameterResidual", value)
    def getDilationParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DilationParameter")
    def setDilationParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("DilationParameter", value)
    def getTensileCutoff(self) -> float:
        return self._propertyAccessor.getDoubleProperty("TensionCutoffValue")
    def setTensileCutoff(self, value: float):
        self._propertyAccessor.setDoubleProperty("TensionCutoffValue", value)
    def getApplySSRShearStrengthReduction(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseSSR")
    def setApplySSRShearStrengthReduction(self, value: bool):
        self._propertyAccessor.setBoolValue("UseSSR", value)
    def getProperties(self):
        return {
            "IntactUCS": self.getIntactUCS(),
            "MbParameter": self.getMbParameter(),
            "SParameter": self.getSParameter(),
            "AParameter": self.getAParameter(),
            "ResidualMbParameter": self.getResidualMbParameter(),
            "ResidualSParameter": self.getResidualSParameter(),
            "ResidualAParameter": self.getResidualAParameter(),
            "DilationParameter": self.getDilationParameter(),
            "TensileCutoff": self.getTensileCutoff(),
            "ApplySSRShearStrengthReduction": self.getApplySSRShearStrengthReduction(),
        }
    def setProperties(self, IntactUCS: float = None, MbParameter: float = None, SParameter: float = None, AParameter: float = None, ResidualMbParameter: float = None, ResidualSParameter: float = None, ResidualAParameter: float = None, DilationParameter: float = None, TensileCutoff: float = None, ApplySSRShearStrengthReduction: bool = None):
        if IntactUCS is not None:
            self.setIntactUCS(IntactUCS)
        if MbParameter is not None:
            self.setMbParameter(MbParameter)
        if SParameter is not None:
            self.setSParameter(SParameter)
        if AParameter is not None:
            self.setAParameter(AParameter)
        if ResidualMbParameter is not None:
            self.setResidualMbParameter(ResidualMbParameter)
        if ResidualSParameter is not None:
            self.setResidualSParameter(ResidualSParameter)
        if ResidualAParameter is not None:
            self.setResidualAParameter(ResidualAParameter)
        if DilationParameter is not None:
            self.setDilationParameter(DilationParameter)
        if TensileCutoff is not None:
            self.setTensileCutoff(TensileCutoff)
        if ApplySSRShearStrengthReduction is not None:
            self.setApplySSRShearStrengthReduction(ApplySSRShearStrengthReduction)
class JointedGeneralizedHoekBrownStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, StrengthStageFactorService_pb2_grpc.StrengthStageFactorServiceStub(client.channel))
    def getAParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_aParameterPeak")
    def getResidualAParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_aParameterResidual")
    def getDilationParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_DilationParameter")
    def getUCSOfIntactRockFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_IntactCompressiveStrength")
    def getMbParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_mbParameterPeak")
    def getResidualMbParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_mbParameterResidual")
    def getSParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_sParameterPeak")
    def getResidualSParameterFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("GenHoekBrown_sParameterResidual")
class JointedGeneralizedHoekBrownDefinedStageFactorBase(JointedGeneralizedHoekBrownStageFactorBase):
    def setAParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_aParameterPeak", value)
    def setResidualAParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_aParameterResidual", value)
    def setDilationParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_DilationParameter", value)
    def setUCSOfIntactRockFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_IntactCompressiveStrength", value)
    def setMbParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_mbParameterPeak", value)
    def setResidualMbParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_mbParameterResidual", value)
    def setSParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_sParameterPeak", value)
    def setResidualSParameterFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("GenHoekBrown_sParameterResidual", value)

################ Code below this line will not be overridden ################
from rs3.properties.material.constitutiveModel.stiffness.LinearIsotropic import LinearIsotropic
from rs3.properties.material.constitutiveModel.stiffness.TransverselyIsotropic import TransverselyIsotropic
from rs3.properties.material.constitutiveModel.stiffness.Orthotropic import Orthotropic
from rs3.properties.material.constitutiveModel.stiffness.DuncanChangHyperbolic import DuncanChangHyperbolic
from rs3.properties.material.constitutiveModel.stiffness.NonlinearIsotropic import NonlinearIsotropic
from rs3.properties.material.constitutiveModel.jointOption.MaterialJointOptions import MaterialJointOptions
from rs3.properties.material.constitutiveModel.UnsaturatedZoneCalculations import UnsaturatedZoneCalculations
from rs3.properties._PropertyAccessor import PropertyAccessor as BasePropertyAccessor
import rs3.generatedFiles.MaterialDataService_pb2_grpc as MaterialDataService_pb2_grpc
import rs3.generatedFiles.MaterialStrengthService_pb2_grpc as MaterialStrengthService_pb2_grpc
from rs3.properties.PropertyEnums import *
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface

class JointedGeneralizedHoekBrownStageFactor(JointedGeneralizedHoekBrownStageFactorBase):
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)

class JointedGeneralizedHoekBrownDefinedStageFactor(JointedGeneralizedHoekBrownDefinedStageFactorBase):
    pass

class JointedGeneralizedHoekBrown(JointedGeneralizedHoekBrownBase):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stub = MaterialStrengthService_pb2_grpc.MaterialStrengthServiceStub(client.channel)
        self._stiffnessPropertyAccessor = BasePropertyAccessor(client, id, MaterialDataService_pb2_grpc.MaterialDataServiceStub(self._client.channel))
        self.LinearIsotropicStiffness = LinearIsotropic(client, id)
        self.TransverselyIsotropicStiffness = TransverselyIsotropic(client, id)
        self.OrthotropicStiffness = Orthotropic(client, id)
        self.DuncanChangHyperbolicStiffness = DuncanChangHyperbolic(client, id)
        self.NonlinearIsotropicStiffness = NonlinearIsotropic(client, id)
        self.UnsaturatedZoneCalculations = UnsaturatedZoneCalculations(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[JointedGeneralizedHoekBrownDefinedStageFactor, JointedGeneralizedHoekBrownStageFactor](id, client, JointedGeneralizedHoekBrownDefinedStageFactor, JointedGeneralizedHoekBrownStageFactor)

    def getElasticType(self) -> MaterialElasticityTypes:
        return self._stiffnessPropertyAccessor.getEnumValue("StiffnessType", MaterialElasticityTypes)
    def setElasticType(self, StiffnessType : MaterialElasticityTypes):
        self._stiffnessPropertyAccessor.setEnumValue("StiffnessType", StiffnessType.value)

    def getMaterialType(self) -> MaterialType:
        return MaterialType(self._propertyAccessor.getBoolValue("IsPlasticForBase"))
    def setMaterialType(self, materialType: MaterialType):
        return self._propertyAccessor.setBoolValue("IsPlasticForBase", materialType.value)

    def getTensileCutoffType(self) -> TensileCutoffOptions:
        return self._propertyAccessor.getEnumValue("TensionCutoff", TensileCutoffOptions)
    def setTensileCutoffType(self, tensionCutoffOption: TensileCutoffOptions):
        return self._propertyAccessor.setEnumValue("TensionCutoff", tensionCutoffOption.value)

    def getJointOptions(self) -> MaterialJointOptions:
        """
        Get all joint option controls.

        Example:
            See :ref:`joint_control_examples`.
            
        >>> material = model.getAllMaterialProperties()[0]
        >>> jointOptions = material.ConstitutiveModel.JointedGeneralizedHoekBrown.getJointOptions()
        >>> jointOptions.setNumberOfJoint(3)
        >>> firstJoint = jointOptions.getJoint(1) 
        """
        return MaterialJointOptions(self._client, self._objectId)
