# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import StiffnessPropertyAccessor, StrengthPropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
class NorsandBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stiffnessPropertyAccessor = StiffnessPropertyAccessor(client, id)
        self._strengthPropertyAccessor = StrengthPropertyAccessor(client, id)
    def getShearModulusAtReferencePressure(self) -> float:
        return self._stiffnessPropertyAccessor.getDoubleProperty("ShearModulusAtRefPressure")
    def setShearModulusAtReferencePressure(self, value: float):
        self._stiffnessPropertyAccessor.setDoubleProperty("ShearModulusAtRefPressure", value)
    def getReferencePressureForShearModulus(self) -> float:
        return self._stiffnessPropertyAccessor.getDoubleProperty("RefPressureForShearModulus")
    def setReferencePressureForShearModulus(self, value: float):
        self._stiffnessPropertyAccessor.setDoubleProperty("RefPressureForShearModulus", value)
    def getModulusExponent(self) -> float:
        return self._stiffnessPropertyAccessor.getDoubleProperty("ModulusExponent")
    def setModulusExponent(self, value: float):
        self._stiffnessPropertyAccessor.setDoubleProperty("ModulusExponent", value)
    def getPoissonsRatio(self) -> float:
        return self._stiffnessPropertyAccessor.getDoubleProperty("PoissonsRatio")
    def setPoissonsRatio(self, value: float):
        self._stiffnessPropertyAccessor.setDoubleProperty("PoissonsRatio", value)
    def getMinimumShearModulus(self) -> float:
        return self._stiffnessPropertyAccessor.getDoubleProperty("MinimumShearModulus")
    def setMinimumShearModulus(self, value: float):
        self._stiffnessPropertyAccessor.setDoubleProperty("MinimumShearModulus", value)
    def getMTCCriticalFrictionRatio(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("CriticalFrictionRatio")
    def setMTCCriticalFrictionRatio(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("CriticalFrictionRatio", value)
    def getLambdaSlopeOfCSLNaturalLog(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("SlopeOfCSL")
    def setLambdaSlopeOfCSLNaturalLog(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("SlopeOfCSL", value)
    def getH0PlasticHardeningModulus(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("PlasticHardeningModulus")
    def setH0PlasticHardeningModulus(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("PlasticHardeningModulus", value)
    def getChiTCDilationCoefficient(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("DilationCoefficient")
    def setChiTCDilationCoefficient(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("DilationCoefficient", value)
    def getNVolumetricCouplingCoefficient(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("VolumetricCouplingCoefficient")
    def setNVolumetricCouplingCoefficient(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("VolumetricCouplingCoefficient", value)
    def getHyChangeInHardeningModulus(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("ChangeInHardeningModulus")
    def setHyChangeInHardeningModulus(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("ChangeInHardeningModulus", value)
    def getPsi0InitialStateParameter(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("InitialStateParameter")
    def setPsi0InitialStateParameter(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("InitialStateParameter", value)
    def getGammaAltitudeOfCSLAt1KPa(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("AltitudeOfCSLAt1kpa")
    def setGammaAltitudeOfCSLAt1KPa(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("AltitudeOfCSLAt1kpa", value)
    def getOCR(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("OverConsolidationRatio")
    def setOCR(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("OverConsolidationRatio", value)
    def getInitialMeanStress(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("InitialMeanStress")
    def setInitialMeanStress(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("InitialMeanStress", value)
    def getCapSoftening(self) -> bool:
        return self._strengthPropertyAccessor.getBoolValue("CapSoftening")
    def setCapSoftening(self, value: bool):
        self._strengthPropertyAccessor.setBoolValue("CapSoftening", value)
    def getNorSandFluidBulkModulus(self) -> float:
        return self._strengthPropertyAccessor.getDoubleProperty("FluidBulkModulus")
    def setNorSandFluidBulkModulus(self, value: float):
        self._strengthPropertyAccessor.setDoubleProperty("FluidBulkModulus", value)
    def getProperties(self):
        return {
            "ShearModulusAtReferencePressure": self.getShearModulusAtReferencePressure(),
            "ReferencePressureForShearModulus": self.getReferencePressureForShearModulus(),
            "ModulusExponent": self.getModulusExponent(),
            "PoissonsRatio": self.getPoissonsRatio(),
            "MinimumShearModulus": self.getMinimumShearModulus(),
            "MTCCriticalFrictionRatio": self.getMTCCriticalFrictionRatio(),
            "LambdaSlopeOfCSLNaturalLog": self.getLambdaSlopeOfCSLNaturalLog(),
            "H0PlasticHardeningModulus": self.getH0PlasticHardeningModulus(),
            "ChiTCDilationCoefficient": self.getChiTCDilationCoefficient(),
            "NVolumetricCouplingCoefficient": self.getNVolumetricCouplingCoefficient(),
            "HyChangeInHardeningModulus": self.getHyChangeInHardeningModulus(),
            "Psi0InitialStateParameter": self.getPsi0InitialStateParameter(),
            "GammaAltitudeOfCSLAt1KPa": self.getGammaAltitudeOfCSLAt1KPa(),
            "OCR": self.getOCR(),
            "InitialMeanStress": self.getInitialMeanStress(),
            "CapSoftening": self.getCapSoftening(),
            "NorSandFluidBulkModulus": self.getNorSandFluidBulkModulus(),
        }
    def setProperties(self, ShearModulusAtReferencePressure: float = None, ReferencePressureForShearModulus: float = None, ModulusExponent: float = None, PoissonsRatio: float = None, MinimumShearModulus: float = None, MTCCriticalFrictionRatio: float = None, LambdaSlopeOfCSLNaturalLog: float = None, H0PlasticHardeningModulus: float = None, ChiTCDilationCoefficient: float = None, NVolumetricCouplingCoefficient: float = None, HyChangeInHardeningModulus: float = None, Psi0InitialStateParameter: float = None, GammaAltitudeOfCSLAt1KPa: float = None, OCR: float = None, InitialMeanStress: float = None, CapSoftening: bool = None, NorSandFluidBulkModulus: float = None):
        if ShearModulusAtReferencePressure is not None:
            self.setShearModulusAtReferencePressure(ShearModulusAtReferencePressure)
        if ReferencePressureForShearModulus is not None:
            self.setReferencePressureForShearModulus(ReferencePressureForShearModulus)
        if ModulusExponent is not None:
            self.setModulusExponent(ModulusExponent)
        if PoissonsRatio is not None:
            self.setPoissonsRatio(PoissonsRatio)
        if MinimumShearModulus is not None:
            self.setMinimumShearModulus(MinimumShearModulus)
        if MTCCriticalFrictionRatio is not None:
            self.setMTCCriticalFrictionRatio(MTCCriticalFrictionRatio)
        if LambdaSlopeOfCSLNaturalLog is not None:
            self.setLambdaSlopeOfCSLNaturalLog(LambdaSlopeOfCSLNaturalLog)
        if H0PlasticHardeningModulus is not None:
            self.setH0PlasticHardeningModulus(H0PlasticHardeningModulus)
        if ChiTCDilationCoefficient is not None:
            self.setChiTCDilationCoefficient(ChiTCDilationCoefficient)
        if NVolumetricCouplingCoefficient is not None:
            self.setNVolumetricCouplingCoefficient(NVolumetricCouplingCoefficient)
        if HyChangeInHardeningModulus is not None:
            self.setHyChangeInHardeningModulus(HyChangeInHardeningModulus)
        if Psi0InitialStateParameter is not None:
            self.setPsi0InitialStateParameter(Psi0InitialStateParameter)
        if GammaAltitudeOfCSLAt1KPa is not None:
            self.setGammaAltitudeOfCSLAt1KPa(GammaAltitudeOfCSLAt1KPa)
        if OCR is not None:
            self.setOCR(OCR)
        if InitialMeanStress is not None:
            self.setInitialMeanStress(InitialMeanStress)
        if CapSoftening is not None:
            self.setCapSoftening(CapSoftening)
        if NorSandFluidBulkModulus is not None:
            self.setNorSandFluidBulkModulus(NorSandFluidBulkModulus)

################ Code below this line will not be overridden ################
from rs3.properties.material.constitutiveModel.UnsaturatedZoneCalculations import UnsaturatedZoneCalculations
from rs3.properties.PropertyEnums import *
class Norsand(NorsandBase):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self.UnsaturatedZoneCalculations = UnsaturatedZoneCalculations(client, id)
        
    def getInitialConsolidationCondition(self) -> NorsandInitialConsolidationConditionType:
        return self._strengthPropertyAccessor.getEnumValue("InitialConsolidationCondition", NorsandInitialConsolidationConditionType)
    def setInitialConsolidationCondition(self, InitialConsolidationCondition: NorsandInitialConsolidationConditionType):
        return self._strengthPropertyAccessor.setEnumValue("InitialConsolidationCondition", InitialConsolidationCondition.value)
