# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
class PowerCurveBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("AParameter")
    def setAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("AParameter", value)
    def getBParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("BParameter")
    def setBParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("BParameter", value)
    def getCParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("CParameter")
    def setCParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("CParameter", value)
    def getDParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DParameter")
    def setDParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("DParameter", value)
    def getWaviness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Waviness")
    def setWaviness(self, value: float):
        self._propertyAccessor.setDoubleProperty("Waviness", value)
    def getResidualAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("AParameterResidual")
    def setResidualAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("AParameterResidual", value)
    def getResidualBParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("BParameterResidual")
    def setResidualBParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("BParameterResidual", value)
    def getResidualCParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("CParameterResidual")
    def setResidualCParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("CParameterResidual", value)
    def getResidualDParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DParameterResidual")
    def setResidualDParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("DParameterResidual", value)
    def getResidualWaviness(self) -> float:
        return self._propertyAccessor.getDoubleProperty("WavinessResidual")
    def setResidualWaviness(self, value: float):
        self._propertyAccessor.setDoubleProperty("WavinessResidual", value)
    def getDilationRatio(self) -> float:
        return self._propertyAccessor.getDoubleProperty("DilationRatio")
    def setDilationRatio(self, value: float):
        self._propertyAccessor.setDoubleProperty("DilationRatio", value)
    def getApplySSRShearStrengthReduction(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseSSR")
    def setApplySSRShearStrengthReduction(self, value: bool):
        self._propertyAccessor.setBoolValue("UseSSR", value)
    def getProperties(self):
        return {
            "AParameter": self.getAParameter(),
            "BParameter": self.getBParameter(),
            "CParameter": self.getCParameter(),
            "DParameter": self.getDParameter(),
            "Waviness": self.getWaviness(),
            "ResidualAParameter": self.getResidualAParameter(),
            "ResidualBParameter": self.getResidualBParameter(),
            "ResidualCParameter": self.getResidualCParameter(),
            "ResidualDParameter": self.getResidualDParameter(),
            "ResidualWaviness": self.getResidualWaviness(),
            "DilationRatio": self.getDilationRatio(),
            "ApplySSRShearStrengthReduction": self.getApplySSRShearStrengthReduction(),
        }
    def setProperties(self, AParameter: float = None, BParameter: float = None, CParameter: float = None, DParameter: float = None, Waviness: float = None, ResidualAParameter: float = None, ResidualBParameter: float = None, ResidualCParameter: float = None, ResidualDParameter: float = None, ResidualWaviness: float = None, DilationRatio: float = None, ApplySSRShearStrengthReduction: bool = None):
        if AParameter is not None:
            self.setAParameter(AParameter)
        if BParameter is not None:
            self.setBParameter(BParameter)
        if CParameter is not None:
            self.setCParameter(CParameter)
        if DParameter is not None:
            self.setDParameter(DParameter)
        if Waviness is not None:
            self.setWaviness(Waviness)
        if ResidualAParameter is not None:
            self.setResidualAParameter(ResidualAParameter)
        if ResidualBParameter is not None:
            self.setResidualBParameter(ResidualBParameter)
        if ResidualCParameter is not None:
            self.setResidualCParameter(ResidualCParameter)
        if ResidualDParameter is not None:
            self.setResidualDParameter(ResidualDParameter)
        if ResidualWaviness is not None:
            self.setResidualWaviness(ResidualWaviness)
        if DilationRatio is not None:
            self.setDilationRatio(DilationRatio)
        if ApplySSRShearStrengthReduction is not None:
            self.setApplySSRShearStrengthReduction(ApplySSRShearStrengthReduction)

################ Code below this line will not be overridden ################
from rs3.properties.material.constitutiveModel.stiffness.LinearIsotropic import LinearIsotropic
from rs3.properties.material.constitutiveModel.stiffness.TransverselyIsotropic import TransverselyIsotropic
from rs3.properties.material.constitutiveModel.stiffness.Orthotropic import Orthotropic
from rs3.properties.material.constitutiveModel.stiffness.DuncanChangHyperbolic import DuncanChangHyperbolic
from rs3.properties.material.constitutiveModel.stiffness.NonlinearIsotropic import NonlinearIsotropic
from rs3.properties.material.constitutiveModel.BaseConstitutiveModel import BaseConstitutiveModel
from rs3.properties.material.constitutiveModel.UnsaturatedZoneCalculations import UnsaturatedZoneCalculations
from rs3.properties._PropertyAccessor import PropertyAccessor as BasePropertyAccessor
import rs3.generatedFiles.MaterialDataService_pb2_grpc as MaterialDataService_pb2_grpc
from rs3.properties.PropertyEnums import *
class PowerCurve(PowerCurveBase, BaseConstitutiveModel):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stiffnessPropertyAccessor = BasePropertyAccessor(client, id, MaterialDataService_pb2_grpc.MaterialDataServiceStub(self._client.channel))
        self.LinearIsotropicStiffness = LinearIsotropic(client, id)
        self.TransverselyIsotropicStiffness = TransverselyIsotropic(client, id)
        self.OrthotropicStiffness = Orthotropic(client, id)
        self.DuncanChangHyperbolicStiffness = DuncanChangHyperbolic(client, id)
        self.NonlinearIsotropicStiffness = NonlinearIsotropic(client, id)
        self.UnsaturatedZoneCalculations = UnsaturatedZoneCalculations(client, id)