# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
class ShansepBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
    def getAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("AParameter")
    def setAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("AParameter", value)
    def getResidualAParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("AParameterRes")
    def setResidualAParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("AParameterRes", value)
    def getSParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("SParameter")
    def setSParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("SParameter", value)
    def getResidualSParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("SParameterRes")
    def setResidualSParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("SParameterRes", value)
    def getMParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("MParameter")
    def setMParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("MParameter", value)
    def getResidualMParameter(self) -> float:
        return self._propertyAccessor.getDoubleProperty("MParameterRes")
    def setResidualMParameter(self, value: float):
        self._propertyAccessor.setDoubleProperty("MParameterRes", value)
    def getMaximumShearStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ShearStrength")
    def setMaximumShearStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("ShearStrength", value)
    def getResidualTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("TensileStrengthRes")
    def setResidualTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("TensileStrengthRes", value)
    def getStressHistoryConstant(self) -> float:
        return self._propertyAccessor.getDoubleProperty("Constant")
    def setStressHistoryConstant(self, value: float):
        self._propertyAccessor.setDoubleProperty("Constant", value)
    def getTensileStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("TensileStrength")
    def setTensileStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("TensileStrength", value)
    def getUseMaximumShearStrength(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseMaxShearStrength")
    def setUseMaximumShearStrength(self, value: bool):
        self._propertyAccessor.setBoolValue("UseMaxShearStrength", value)
    def getUseTensileStrength(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseTensileStrength")
    def setUseTensileStrength(self, value: bool):
        self._propertyAccessor.setBoolValue("UseTensileStrength", value)
    def getUseMaterialDependentStress(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseMaterialDependantStress")
    def setUseMaterialDependentStress(self, value: bool):
        self._propertyAccessor.setBoolValue("UseMaterialDependantStress", value)
    def getResidualMaximumShearStrength(self) -> float:
        return self._propertyAccessor.getDoubleProperty("ShearStrengthRes")
    def setResidualMaximumShearStrength(self, value: float):
        self._propertyAccessor.setDoubleProperty("ShearStrengthRes", value)
    def getApplySSRShearStrengthReduction(self) -> bool:
        return self._propertyAccessor.getBoolValue("UseSSR")
    def setApplySSRShearStrengthReduction(self, value: bool):
        self._propertyAccessor.setBoolValue("UseSSR", value)
    def getProperties(self):
        return {
            "AParameter": self.getAParameter(),
            "ResidualAParameter": self.getResidualAParameter(),
            "SParameter": self.getSParameter(),
            "ResidualSParameter": self.getResidualSParameter(),
            "MParameter": self.getMParameter(),
            "ResidualMParameter": self.getResidualMParameter(),
            "MaximumShearStrength": self.getMaximumShearStrength(),
            "ResidualTensileStrength": self.getResidualTensileStrength(),
            "StressHistoryConstant": self.getStressHistoryConstant(),
            "TensileStrength": self.getTensileStrength(),
            "UseMaximumShearStrength": self.getUseMaximumShearStrength(),
            "UseTensileStrength": self.getUseTensileStrength(),
            "UseMaterialDependentStress": self.getUseMaterialDependentStress(),
            "ResidualMaximumShearStrength": self.getResidualMaximumShearStrength(),
            "ApplySSRShearStrengthReduction": self.getApplySSRShearStrengthReduction(),
        }
    def setProperties(self, AParameter: float = None, ResidualAParameter: float = None, SParameter: float = None, ResidualSParameter: float = None, MParameter: float = None, ResidualMParameter: float = None, MaximumShearStrength: float = None, ResidualTensileStrength: float = None, StressHistoryConstant: float = None, TensileStrength: float = None, UseMaximumShearStrength: bool = None, UseTensileStrength: bool = None, UseMaterialDependentStress: bool = None, ResidualMaximumShearStrength: float = None, ApplySSRShearStrengthReduction: bool = None):
        if AParameter is not None:
            self.setAParameter(AParameter)
        if ResidualAParameter is not None:
            self.setResidualAParameter(ResidualAParameter)
        if SParameter is not None:
            self.setSParameter(SParameter)
        if ResidualSParameter is not None:
            self.setResidualSParameter(ResidualSParameter)
        if MParameter is not None:
            self.setMParameter(MParameter)
        if ResidualMParameter is not None:
            self.setResidualMParameter(ResidualMParameter)
        if MaximumShearStrength is not None:
            self.setMaximumShearStrength(MaximumShearStrength)
        if ResidualTensileStrength is not None:
            self.setResidualTensileStrength(ResidualTensileStrength)
        if StressHistoryConstant is not None:
            self.setStressHistoryConstant(StressHistoryConstant)
        if TensileStrength is not None:
            self.setTensileStrength(TensileStrength)
        if UseMaximumShearStrength is not None:
            self.setUseMaximumShearStrength(UseMaximumShearStrength)
        if UseTensileStrength is not None:
            self.setUseTensileStrength(UseTensileStrength)
        if UseMaterialDependentStress is not None:
            self.setUseMaterialDependentStress(UseMaterialDependentStress)
        if ResidualMaximumShearStrength is not None:
            self.setResidualMaximumShearStrength(ResidualMaximumShearStrength)
        if ApplySSRShearStrengthReduction is not None:
            self.setApplySSRShearStrengthReduction(ApplySSRShearStrengthReduction)

################ Code below this line will not be overridden ################
from rs3.properties.material.constitutiveModel.stiffness.LinearIsotropic import LinearIsotropic
from rs3.properties.material.constitutiveModel.stiffness.TransverselyIsotropic import TransverselyIsotropic
from rs3.properties.material.constitutiveModel.stiffness.Orthotropic import Orthotropic
from rs3.properties.material.constitutiveModel.stiffness.DuncanChangHyperbolic import DuncanChangHyperbolic
from rs3.properties.material.constitutiveModel.stiffness.NonlinearIsotropic import NonlinearIsotropic
from rs3.properties.material.constitutiveModel.BaseConstitutiveModel import BaseConstitutiveModel
from rs3.properties.material.constitutiveModel.UnsaturatedZoneCalculations import UnsaturatedZoneCalculations
from rs3.properties._PropertyAccessor import PropertyAccessor as BasePropertyAccessor
import rs3.generatedFiles.MaterialDataService_pb2_grpc as MaterialDataService_pb2_grpc
import rs3.generatedFiles.MaterialStrengthService_pb2_grpc as MaterialStrengthService_pb2_grpc
import rs3.generatedFiles.MaterialStrengthService_pb2 as MaterialStrengthService_pb2
from rs3.properties.PropertyEnums import *
class Shansep(ShansepBase, BaseConstitutiveModel):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._stub = MaterialStrengthService_pb2_grpc.MaterialStrengthServiceStub(client.channel)
        self._stiffnessPropertyAccessor = BasePropertyAccessor(client, id, MaterialDataService_pb2_grpc.MaterialDataServiceStub(self._client.channel))
        self.LinearIsotropicStiffness = LinearIsotropic(client, id)
        self.TransverselyIsotropicStiffness = TransverselyIsotropic(client, id)
        self.OrthotropicStiffness = Orthotropic(client, id)
        self.DuncanChangHyperbolicStiffness = DuncanChangHyperbolic(client, id)
        self.NonlinearIsotropicStiffness = NonlinearIsotropic(client, id)
        self.UnsaturatedZoneCalculations = UnsaturatedZoneCalculations(client, id)
        
    def getStressHistoryType(self) -> StressHistoryTypes:
        return self._propertyAccessor.getEnumValue("StressHistoryType", StressHistoryTypes)
    def setStressHistoryType(self, StressHistoryType: StressHistoryTypes):
        return self._propertyAccessor.setEnumValue("StressHistoryType", StressHistoryType.value)

    def getStressHistoryTypeMethod(self) -> StressHistoryDefinitionMethods:
        return self._propertyAccessor.getEnumValue("StressHistoryTypeMethod", StressHistoryDefinitionMethods)
    def setStressHistoryTypeMethod(self, StressHistoryTypeMethod: StressHistoryDefinitionMethods):
        return self._propertyAccessor.setEnumValue("StressHistoryTypeMethod", StressHistoryTypeMethod.value)
    
    def getShansepMaterialDependentVerticalStress(self) -> list[tuple[str, float]]:
        """
        Retrieve the material dependant stress function points for the current material.

        Returns:
            list[tuple[str, float]]:
                A list of tuples, where each tuple contains:
                - materialName (str): The material name.
                - vertucalStressFactor (float): The corresponding vertical stress factor.
        """
        request = MaterialStrengthService_pb2.GetMaterialDependentVerticalStressFactorPropertyRequest(objectId=self._objectId)
        response : MaterialStrengthService_pb2.GetMaterialDependentVerticalStressFactorPropertyResponse = self._client.callFunction(self._stub.GetMaterialDependentVerticalStressFactorProperty, request)
        return list((p.materialName, p.verticalStessFactor) for p in response.point)
    def setShansepMaterialDependentVerticalStress(self, value: list[tuple[str, float]]):
        """
        Set the material dependant stress function points for the current material.

        Args:
            value (list[tuple[str, float]]):
                A list of tuples, where each tuple contains:
                - materialName (str): The material name.
                - vertucalStressFactor (float): The corresponding vertical stress factor.
        """
        materialDependentStressList = []
        for materialName, verticalStessFactor in value:
            verticalStressPoint = MaterialStrengthService_pb2.MaterialDependentVerticalStressPoint(materialName=materialName, verticalStessFactor=verticalStessFactor)
            materialDependentStressList.append(verticalStressPoint)
        request = MaterialStrengthService_pb2.SetMaterialDependentVerticalStressFactorPropertyRequest(objectId=self._objectId, point=materialDependentStressList)
        self._client.callFunction(self._stub.SetMaterialDependentVerticalStressFactorProperty, request)
        
    def getShansepStressHistory(self) -> list[tuple[float, float]]:
        """
        Retrieve the stress history points for the current material.

        Returns:
            list[tuple[float, float]]:
                A list of tuples, where each tuple contains:
                - depth/elevation (float): The depth or elevation value.
                - OCR/Pc (float): The corresponding overconsolidation ratio (OCR) value or preconsolidation pressure.
        """
        request = MaterialStrengthService_pb2.GetStressHistoryPropertyRequest(objectId=self._objectId)
        response : MaterialStrengthService_pb2.GetStressHistoryPropertyResponse = self._client.callFunction(self._stub.GetStressHistoryProperty, request)
        return (StressHistoryDefinitionMethods(response.header.column1), StressHistoryTypes(response.header.column2)), [(p.z, p.stressHistoryVal) for p in response.point]
    def setShansepStressHistory(self, headerList : tuple[StressHistoryDefinitionMethods, StressHistoryTypes], value: list[tuple[float, float]]):
        """
        Set the stress history function points for the current material.

        Args:
            value (list[tuple[float, float]]):
                A list of tuples, where each tuple contains:
                - depth/elevation (float): The depth or elevation value.
                - OCR/Pc (float): The corresponding overconsolidation ratio (OCR) value or preconsolidation pressure.
        """
        stressHistoryList = []
        for z, stressHistoryVal in value:
            verticalStressPoint = MaterialStrengthService_pb2.StressHistoryPoint(z=z, stressHistoryVal=stressHistoryVal)
            stressHistoryList.append(verticalStressPoint)
        headerListVal = MaterialStrengthService_pb2.StressHistoryHeader(column1=headerList[0].value, column2=headerList[1].value)
        request = MaterialStrengthService_pb2.SetStressHistoryPropertyRequest(objectId=self._objectId, header=headerListVal, point=stressHistoryList)
        self._client.callFunction(self._stub.SetStressHistoryProperty, request)