# Generated by RPCBinder in RFC_Common.
from rs3._client import Client
from ._PropertyAccessor import PropertyAccessor, UnloadingPropertyAccessor
from rs3._proxyObject import _ProxyObject
from rs3.properties.IPropertyGroupAccessors import IPropertyGroupAccessors
from rs3.properties.stageFactors.IStageFactorBase import IStageFactorBase
import rs3.generatedFiles.StiffnessStageFactorService_pb2_grpc as StiffnessStageFactorService_pb2_grpc
class NonlinearIsotropicBase(_ProxyObject, IPropertyGroupAccessors):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._propertyAccessor = PropertyAccessor(client, id)
        self._unloadingPropertyAccessor = UnloadingPropertyAccessor(client, id)
    def getPoissonsRatio(self) -> float:
        return self._propertyAccessor.getDoubleProperty("PoissonsRatio")
    def setPoissonsRatio(self, value: float):
        self._propertyAccessor.setDoubleProperty("PoissonsRatio", value)
    def getUseResidualYoungsModulus(self) -> bool:
        return self._propertyAccessor.getBoolValue("UsesYoungsModulusResidual")
    def setUseResidualYoungsModulus(self, value: bool):
        self._propertyAccessor.setBoolValue("UsesYoungsModulusResidual", value)
    def getResidualYoungsModulus(self) -> float:
        return self._propertyAccessor.getDoubleProperty("YoungsModulusResidual")
    def setResidualYoungsModulus(self, value: float):
        self._propertyAccessor.setDoubleProperty("YoungsModulusResidual", value)
    def getUnloadingPoissonsRatio(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("PoissonsRatio")
    def setUnloadingPoissonsRatio(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("PoissonsRatio", value)
    def getUnloadingUseResidualYoungsModulus(self) -> bool:
        return self._unloadingPropertyAccessor.getBoolValue("UsesYoungsModulusResidual")
    def setUnloadingUseResidualYoungsModulus(self, value: bool):
        self._unloadingPropertyAccessor.setBoolValue("UsesYoungsModulusResidual", value)
    def getUnloadingResidualYoungsModulus(self) -> float:
        return self._unloadingPropertyAccessor.getDoubleProperty("YoungsModulusResidual")
    def setUnloadingResidualYoungsModulus(self, value: float):
        self._unloadingPropertyAccessor.setDoubleProperty("YoungsModulusResidual", value)
    def getProperties(self):
        return {
            "PoissonsRatio": self.getPoissonsRatio(),
            "UseResidualYoungsModulus": self.getUseResidualYoungsModulus(),
            "ResidualYoungsModulus": self.getResidualYoungsModulus(),
            "UnloadingPoissonsRatio": self.getUnloadingPoissonsRatio(),
            "UnloadingUseResidualYoungsModulus": self.getUnloadingUseResidualYoungsModulus(),
            "UnloadingResidualYoungsModulus": self.getUnloadingResidualYoungsModulus(),
        }
    def setProperties(self, PoissonsRatio: float = None, UseResidualYoungsModulus: bool = None, ResidualYoungsModulus: float = None, UnloadingPoissonsRatio: float = None, UnloadingUseResidualYoungsModulus: bool = None, UnloadingResidualYoungsModulus: float = None):
        if PoissonsRatio is not None:
            self.setPoissonsRatio(PoissonsRatio)
        if UseResidualYoungsModulus is not None:
            self.setUseResidualYoungsModulus(UseResidualYoungsModulus)
        if ResidualYoungsModulus is not None:
            self.setResidualYoungsModulus(ResidualYoungsModulus)
        if UnloadingPoissonsRatio is not None:
            self.setUnloadingPoissonsRatio(UnloadingPoissonsRatio)
        if UnloadingUseResidualYoungsModulus is not None:
            self.setUnloadingUseResidualYoungsModulus(UnloadingUseResidualYoungsModulus)
        if UnloadingResidualYoungsModulus is not None:
            self.setUnloadingResidualYoungsModulus(UnloadingResidualYoungsModulus)
class NonlinearIsotropicStageFactorBase(IStageFactorBase):
    def __init__(self, id : str, stageFactorID : str, client : Client):
        super().__init__(id, stageFactorID, client, StiffnessStageFactorService_pb2_grpc.StiffnessStageFactorServiceStub(client.channel))
    def getPoissonsRatioFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("NonLinear_PoissonsRatio")
    def getResidualYoungsModulusFactor(self) -> float:
        return self._stageFactorPropertyAccessor.getDoubleProperty("NonLinear_YoungsModulusResidual")
class NonlinearIsotropicDefinedStageFactorBase(NonlinearIsotropicStageFactorBase):
    def setPoissonsRatioFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("NonLinear_PoissonsRatio", value)
    def setResidualYoungsModulusFactor(self, value: float):
        self._stageFactorPropertyAccessor.setDoubleProperty("NonLinear_YoungsModulusResidual", value)

################ Code below this line will not be overridden ################
from rs3.properties.PropertyEnums import *
from rs3.properties.material.constitutiveModel.stiffness.GeneralizedHoekBrownEstimation import GeneralizedHoekBrownEstimation
from rs3.properties.material.constitutiveModel.stiffness.formula.Formula1 import Formula1
from rs3.properties.material.constitutiveModel.stiffness.formula.Formula2 import Formula2
from rs3.properties.material.constitutiveModel.stiffness.formula.Formula3 import Formula3
from rs3.properties.material.constitutiveModel.stiffness.BaseStiffness import BaseStiffness
from ._PropertyAccessor import LoadingPropertyAccessor, UnloadingPropertyAccessor
from rs3.properties.stageFactors.StageFactorBaseInterfaces import AbsoluteStageFactorInterface

class NonlinearIsotropicStageFactor(NonlinearIsotropicStageFactorBase):
    def __init__(self, id: str, stageFactorId: str, client: Client):
        super().__init__(id, stageFactorId, client)
        
class NonlinearIsotropicDefinedStageFactor(NonlinearIsotropicDefinedStageFactorBase):
    pass

class NonlinearIsotropic(NonlinearIsotropicBase, BaseStiffness):
    def __init__(self, client: Client, id: str):
        super().__init__(client, id)
        self._basePropertyAccessor = PropertyAccessor(client, id)
        self._propertyAccessor = LoadingPropertyAccessor(client, id)
        self.Formula1 = Formula1(client, id)
        self.Formula2 = Formula2(client, id)
        self.Formula3 = Formula3(client, id)
        self.GeneralizedHoekBrownEstimation = GeneralizedHoekBrownEstimation(client, id)
        self.StageFactorInterface = AbsoluteStageFactorInterface[NonlinearIsotropicDefinedStageFactor, NonlinearIsotropicStageFactor](id, client, NonlinearIsotropicDefinedStageFactor, NonlinearIsotropicStageFactor)
        
    def getNonLinearIsotropicFormula(self) -> NonlinearIsotropicFormulaType:
        return self._basePropertyAccessor.getEnumValue("FormulaSource", NonlinearIsotropicFormulaType)  
    def setNonLinearIsotropicFormula(self, formulaSource : NonlinearIsotropicFormulaType):
        self._basePropertyAccessor.setEnumValue("FormulaSource", formulaSource.value)
        